import 'package:flutter/material.dart';

class Ksclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Ksclist(
    {
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
    }
  );
}
final KedahStateClinicList=[
  Ksclist(
    titletext: 'KLINIK SAFIYA 24 JAM',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SAFIYA 24 JAM',
    address: 'Address',
    clinicaddress: 'NO. 5, JALAN KLC1 KULIM LANDMARK CENTRAL',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK SAFIYA & SURGERI-KULIM AVENUE',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SAFIYA & SURGERI-KULIM AVENUE',
    address: 'Address',
    clinicaddress: 'NO.21, GROUND FLOOR, PERSIARAN 1, KULIM AVENUE, KULIM HI- TECH PARK',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK MEDIK SP SDN BHD',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIK SP SDN BHD',
    address: 'Address',
    clinicaddress: 'NO.104, TINGKAT BAWAH, JALAN BATIK 2/3, TAMAN BATIK',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK HIDAYAH',
    subtitletext: 'ALOR SETAR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK HIDAYAH',
    address: 'Address',
    clinicaddress: '33, JALAN PERSIARAN SULTAN ABD HAMID, KOMPLEKS SULTAN ABDUL HAMID',
    location: 'Location',
    cliniclocation: 'ALOR SETAR',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'MEDIKLINIK RAKYAT DR NAIM AHMAD',
    subtitletext: 'ALOR SETAR',
    clinic: 'Clinic Name',
    clinicname: 'MEDIKLINIK RAKYAT DR NAIM AHMAD',
    address: 'Address',
    clinicaddress: 'LOT5A, PT III, KOMPLEKS PERNIAGAAN AMPANG, LEBUHRAYA SULTANAH BAHIYAH',
    location: 'Location',
    cliniclocation: 'ALOR SETAR',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK CINTA SAYANG',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CINTA SAYANG',
    address: 'Address',
    clinicaddress: '15, JALAN PERMATANG GEDONG, TAMAN SEJATI INDAH',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK DR HALIMAH - GURUN',
    subtitletext: 'GURUN',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DR HALIMAH - GURUN',
    address: 'Address',
    clinicaddress: 'NO.24, TINGKAT BAWAH, JALAN JERAI MAJU 1A, TAMAN JERAI MAJU 11',
    location: 'Location',
    cliniclocation: 'GURUN',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK DR HALIMAH - SG PETANI',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DR HALIMAH - SG PETANI',
    address: 'Address',
    clinicaddress: 'NO.120, TINGKAT BAWAH, JALAN BANDAR PUTERI JAYA 1/1, BANDAR PUTERI JAYA',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK DR HALIMAH - BALING',
    subtitletext: 'BALING',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DR HALIMAH - BALING',
    address: 'Address',
    clinicaddress: 'NO.132B, PERSIARAN KOTA 5/5, KOTA BALING JAYA, BATU 42, PULAI',
    location: 'Location',
    cliniclocation: 'BALING',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK DR HALIMAH - KUALA KETIL',
    subtitletext: 'KUALA KETIL',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DR HALIMAH - KUALA KETIL',
    address: 'Address',
    clinicaddress: 'NO.18/B, BANGUNAN PKNK, JALAN BALING',
    location: 'Location',
    cliniclocation: 'KUALA KETIL',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK RAKYAT',
    subtitletext: 'KUALA NERANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAKYAT',
    address: 'Address',
    clinicaddress: 'NO.60A, PEKAN BARU KUALA NERANG',
    location: 'Location',
    cliniclocation: 'KUALA NERANG',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK SANAN',
    subtitletext: 'GURUN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SANAN',
    address: 'Address',
    clinicaddress: '18, TAMAN MEWAH, GUAR CHEMPEDAK',
    location: 'Location',
    cliniclocation: 'GURUN',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK DR CHENG',
    subtitletext: 'KUALA KEDAH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR CHENG',
    address: 'Address',
    clinicaddress: 'NO.47, TINGKAT BAWAH, TAMAN JOHAN FASA 2, JALAN KUALA KEDAH',
    location: 'Location',
    cliniclocation: 'KUALA KEDAH',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK WAWASAN - KULIM',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK WAWASAN - KULIM',
    address: 'Address',
    clinicaddress: 'NO.10, JALAN RAYA',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK VIGNESHWER',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK VIGNESHWER',
    address: 'Address',
    clinicaddress: '5004, BATU 2 1/2, JALAN LUNAS',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK PARTHEEBAN',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PARTHEEBAN',
    address: 'Address',
    clinicaddress: 'NO.B6, JALAN KENARI BIRU 1, TAMAN KENARI JAYA 2',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK NGA N. HOO',
    subtitletext: 'POKOK SENA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK NGA N. HOO',
    address: 'Address',
    clinicaddress: '1912D, PEKAN POKOK SENA,',
    location: 'Location',
    cliniclocation: 'POKOK SENA',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK MEDIK JAYA SDN BHD',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIK JAYA SDN BHD',
    address: 'Address',
    clinicaddress: 'NO.11, TINGKAT BAWAH, LORONG 13, TAMAN PETANI JAYA',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK SAKTHI N SHEILA SDN BHD',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SAKTHI N SHEILA SDN BHD',
    address: 'Address',
    clinicaddress: '65, PERSIARAN 1, KULIM AVENUE, KULIM HI-TECH PARK',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK MESRA',
    subtitletext: 'ALOR SETAR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MESRA',
    address: 'Address',
    clinicaddress: 'NO.4, (GF), PUSAT PERDAGANGAN TUNKU HAMINAH, MERGONG',
    location: 'Location',
    cliniclocation: 'ALOR SETAR',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK FAISAL HAMDI',
    subtitletext: 'ALOR SETAR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAISAL HAMDI',
    address: 'Address',
    clinicaddress: '938, JALAN SULTAN BADLISHAH',
    location: 'Location',
    cliniclocation: 'ALOR SETAR',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLYCLINIC GY - TAMAN NENAS',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'POLYCLINIC GY - TAMAN NENAS',
    address: 'Address',
    clinicaddress: 'NO.209, TINGKAT BAWAH, JALAN KELANG LAMA, TAMAN NENAS',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK GY3 - BANDAR MUTIARA',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK GY3 - BANDAR MUTIARA',
    address: 'Address',
    clinicaddress: 'NO.739, GROUND FLOOR, JALAN BM 1/1, BANDAR MUTIARA',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLYCLINIC GY - TAMAN DAMAI',
    subtitletext: 'PADANG SERAI',
    clinic: 'Clinic Name',
    clinicname: 'POLYCLINIC GY - TAMAN DAMAI',
    address: 'Address',
    clinicaddress: '70, JALAN DAMAI 3, TAMAN DAMAI',
    location: 'Location',
    cliniclocation: 'PADANG SERAI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLYCLINIC GY - DESA AMAN',
    subtitletext: 'PADANG SERAI',
    clinic: 'Clinic Name',
    clinicname: 'POLYCLINIC GY - DESA AMAN',
    address: 'Address',
    clinicaddress: '54, JALAN DESA AMAN S2/2, TAMAN DESA AMAN',
    location: 'Location',
    cliniclocation: 'PADANG SERAI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK SAKTHI N SHEILA SDN BHD',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SAKTHI N SHEILA SDN BHD',
    address: 'Address',
    clinicaddress: '65, PERSIARAN 1, KULIM AVENUE, KULIM HI-TECH PARK',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK MESRA',
    subtitletext: 'ALOR SETAR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MESRA',
    address: 'Address',
    clinicaddress: 'NO.4, (GF), PUSAT PERDAGANGAN TUNKU HAMINAH, MERGONG',
    location: 'Location',
    cliniclocation: 'ALOR SETAR',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK FAISAL HAMDI',
    subtitletext: 'ALOR SETAR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAISAL HAMDI',
    address: 'Address',
    clinicaddress: '938, JALAN SULTAN BADLISHAH',
    location: 'Location',
    cliniclocation: 'ALOR SETAR',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLYCLINIC GY - TAMAN NENAS',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'POLYCLINIC GY - TAMAN NENAS',
    address: 'Address',
    clinicaddress: 'NO.209, TINGKAT BAWAH, JALAN KELANG LAMA, TAMAN NENAS',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK GY3 - BANDAR MUTIARA',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK GY3 - BANDAR MUTIARA',
    address: 'Address',
    clinicaddress: 'NO.739, GROUND FLOOR, JALAN BM 1/1, BANDAR MUTIARA',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLYCLINIC GY - TAMAN DAMAI',
    subtitletext: 'PADANG SERAI',
    clinic: 'Clinic Name',
    clinicname: 'POLYCLINIC GY - TAMAN DAMAI',
    address: 'Address',
    clinicaddress: '70, JALAN DAMAI 3, TAMAN DAMAI',
    location: 'Location',
    cliniclocation: 'PADANG SERAI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLYCLINIC GY - DESA AMAN',
    subtitletext: 'PADANG SERAI',
    clinic: 'Clinic Name',
    clinicname: 'POLYCLINIC GY - DESA AMAN',
    address: 'Address',
    clinicaddress: '54, JALAN DESA AMAN S2/2, TAMAN DESA AMAN',
    location: 'Location',
    cliniclocation: 'PADANG SERAI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLYCLINIC GY - TAMAN DESA PERMAI II',
    subtitletext: 'LUNAS',
    clinic: 'Clinic Name',
    clinicname: 'POLYCLINIC GY - TAMAN DESA PERMAI II',
    address: 'Address',
    clinicaddress: 'NO.271, TAMAN DESA PERMAI II',
    location: 'Location',
    cliniclocation: 'LUNAS',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK SOMA',
    subtitletext: 'ALOR SETAR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SOMA',
    address: 'Address',
    clinicaddress: '931, JALAN SULTAN BADLISHAH',
    location: 'Location',
    cliniclocation: 'ALOR SETAR',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK BERSATU - TAMAN SERULING',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BERSATU - TAMAN SERULING',
    address: 'Address',
    clinicaddress: '7, JALAN SERULING 1A, TAMAN SERULING',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK RAPHA',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAPHA',
    address: 'Address',
    clinicaddress: '471, JALAN KOTA KENARI 3, KOTA KENARI',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK DR CHUA SDN BHD',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR CHUA SDN BHD',
    address: 'Address',
    clinicaddress: '125, JALAN LAGENDA 4, LAGENDA HEIGHTS',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK TEOH KIM YONG',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK TEOH KIM YONG',
    address: 'Address',
    clinicaddress: 'NO.35-E, TAMAN AMAN II',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'MAHA KLINIK SDN BHD',
    subtitletext: 'ALOR SETAR',
    clinic: 'Clinic Name',
    clinicname: 'MAHA KLINIK SDN BHD',
    address: 'Address',
    clinicaddress: '1587, JALAN SULTAN BADLISHAH',
    location: 'Location',
    cliniclocation: 'ALOR SETAR',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK DR ARIFAH',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR ARIFAH',
    address: 'Address',
    clinicaddress: 'NO.19 (GF), TAMAN TEMUSU',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK KULIM',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KULIM',
    address: 'Address',
    clinicaddress: 'NO.27, JALAN RAYA',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK MESRA - GURUN',
    subtitletext: 'GURUN',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK MESRA - GURUN',
    address: 'Address',
    clinicaddress: 'NO.11, LORONG 1, TAMAN RIA MESRA 2',
    location: 'Location',
    cliniclocation: 'GURUN',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK DR.ROSNANI',
    subtitletext: 'GURUN',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DR.ROSNANI',
    address: 'Address',
    clinicaddress: 'NO.10A PEKAN JENIANG',
    location: 'Location',
    cliniclocation: 'GURUN',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK DR.AKBAR',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.AKBAR',
    address: 'Address',
    clinicaddress: 'NO.9 LEBUH FAIRUZ 1 TAMAN PERUSAHAAN RINGAN BAKAR ARANG',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'KLINIK PRIMA MEDIC',
    subtitletext: 'KULIM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PRIMA MEDIC',
    address: 'Address',
    clinicaddress: '5009, BATU 2 1/2, JALAN LUNAS, KELANG LAMA',
    location: 'Location',
    cliniclocation: 'KULIM',
    state: 'State',
    nameofstate: 'Kedah',
    ),
    Ksclist(
    titletext: 'POLIKLINIK & SURGERI RIA JAYA SDN BHD',
    subtitletext: 'SUNGAI PETANI',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK & SURGERI RIA JAYA SDN BHD',
    address: 'Address',
    clinicaddress: 'NO.175, TONGKAT BAWAH, JALAN CINTA SAYANG, TAMAN RIA JAYA',
    location: 'Location',
    cliniclocation: 'SUNGAI PETANI',
    state: 'State',
    nameofstate: 'Kedah',
    ),
];