import 'package:flutter/material.dart';

class Msclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Msclist(
    {
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
    }
  );
}
final MelakaStateClinicList=[
  Msclist(
    titletext: 'MEGAKLINIK ZAHRAN - BANDARAYA MELAKA',
    subtitletext: 'MELAKA',
    clinic: 'Clinic Name',
    clinicname: 'MEGAKLINIK ZAHRAN - BANDARAYA MELAKA',
    address: 'Address',
    clinicaddress: 'NO.5, JALAN SETIA TROPIKA 1/28, TAMAN SETIA TROPIKA, KEMPAS',
    location: 'Location',
    cliniclocation: 'MELAKA',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK PENAWAR & PEMBEDAHAN',
    subtitletext: 'JASIN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PENAWAR & PEMBEDAHAN',
    address: 'Address',
    clinicaddress: 'JC - 534, JALAN BESTARI 5, BANDAR JASIN BESTARI SEKSYEN 2, JASIN',
    location: 'Location',
    cliniclocation: 'JASIN',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'CARING MEDICAL SPECIALIST CLINIC',
    subtitletext: 'BATU BERENDAM',
    clinic: 'Clinic Name',
    clinicname: 'CARING MEDICAL SPECIALIST CLINIC',
    address: 'Address',
    clinicaddress: '79, JALAN MP1, TAMAN MERDEKA PERMAI, BATU BERENDAM',
    location: 'Location',
    cliniclocation: 'BATU BERENDAM',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK KOK DAN SEGERI',
    subtitletext: 'PULAU SEBANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KOK DAN SEGERI',
    address: 'Address',
    clinicaddress: '4357, JALAN BESAR PULAU SEBANG, TAMPIN',
    location: 'Location',
    cliniclocation: 'PULAU SEBANG',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK MELAKA JAYA',
    subtitletext: 'MELAKA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MELAKA JAYA',
    address: 'Address',
    clinicaddress: 'NO.36, JALAN MELAKA RAYA 14, TAMAN MELAKA RAYA',
    location: 'Location',
    cliniclocation: 'MELAKA',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK LAI',
    subtitletext: 'BATU BERENDAM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK LAI',
    address: 'Address',
    clinicaddress: 'NO.39, JALAN MELAKA BARU 22, TAMAN MELAKA BARU, BATU BERENDAM',
    location: 'Location',
    cliniclocation: 'BATU BERENDAM',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK DR FAUZI',
    subtitletext: 'TANJONG MINYAK',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR FAUZI',
    address: 'Address',
    clinicaddress: 'NO.11, JALAN RJ 29, TAMAN RAMBAI JAYA, TANJONG MINYAK',
    location: 'Location',
    cliniclocation: 'TANJONG MINYAK',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK SRIMAS & SURGERI',
    subtitletext: 'CHENG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SRIMAS & SURGERI',
    address: 'Address',
    clinicaddress: 'NO.39, JALAN CP 1/21A, JALAN TAMAN CHENG PERDANA',
    location: 'Location',
    cliniclocation: 'CHENG',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'POLIKLINIK & SURGERI MERLIMAU',
    subtitletext: 'MERLIMAU',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK & SURGERI MERLIMAU',
    address: 'Address',
    clinicaddress: 'JA 1464, TAMAN MUHIBAH II',
    location: 'Location',
    cliniclocation: 'MERLIMAU',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK & SURGERI SEMABOK PERDANA',
    subtitletext: 'SEMABOK',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK & SURGERI SEMABOK PERDANA',
    address: 'Address',
    clinicaddress: 'NO.11 & 13, JALAN SP 1, TAMAN SEMABOK PERDANA',
    location: 'Location',
    cliniclocation: 'SEMABOK',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK SOHVINDIR',
    subtitletext: 'BATU BERENDAM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SOHVINDIR',
    address: 'Address',
    clinicaddress: '78,80, JALAN MUTIARA MELAKA 2, BATU BERENDAM',
    location: 'Location',
    cliniclocation: 'BATU BERENDAM',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'POLIKLINIK BANDAR SDN BHD',
    subtitletext: 'MELAKA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK BANDAR SDN BHD',
    address: 'Address',
    clinicaddress: '33-35, JALAN BANDA KABA',
    location: 'Location',
    cliniclocation: 'MELAKA',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK KOTA LAKSAMANA',
    subtitletext: 'MELAKA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KOTA LAKSAMANA',
    address: 'Address',
    clinicaddress: 'NO.17, JALAN KL 3/15, TAMAN KOTA LAKSAMANA SEK 3',
    location: 'Location',
    cliniclocation: 'MELAKA',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK UTAMA CHENG',
    subtitletext: 'PAYA RUMPUT',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK UTAMA CHENG',
    address: 'Address',
    clinicaddress: 'NO.17, JALAN INANG 3, TAMAN PAYA RUMPUT UTAMA',
    location: 'Location',
    cliniclocation: 'PAYA RUMPUT',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK CHUA - TAMPIN',
    subtitletext: 'TAMPIN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CHUA - TAMPIN',
    address: 'Address',
    clinicaddress: '3177, MAIN ROAD, TAMPIN',
    location: 'Location',
    cliniclocation: 'TAMPIN',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK 1 KRUBONG',
    subtitletext: 'KRUBONG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK 1 KRUBONG',
    address: 'Address',
    clinicaddress: 'NO.119, JALAN SATU KRUBONG, TAMAN SATU KRUBONG',
    location: 'Location',
    cliniclocation: 'KRUBONG',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK RAJ (JASIN) SDN BHD',
    subtitletext: 'JASIN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAJ (JASIN) SDN BHD',
    address: 'Address',
    clinicaddress: '57, MAIN ROAD,',
    location: 'Location',
    cliniclocation: 'JASIN',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'POLIKLINIK BUKIT KATIL',
    subtitletext: 'MELAKA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK BUKIT KATIL',
    address: 'Address',
    clinicaddress: 'NO.11 & 11.1, JALAN SAUJANA 2/2, TAMAN SAUJANA SEKSYEN 2,',
    location: 'Location',
    cliniclocation: 'MELAKA',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK AMAL & SURGERI SDN BHD',
    subtitletext: 'BUKIT KATIL',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK AMAL & SURGERI SDN BHD',
    address: 'Address',
    clinicaddress: '9, PUSAT NIAGA GUKIT KATIL, JALAN TUN KUDU BUKIT KATIL',
    location: 'Location',
    cliniclocation: 'BUKIT KATIL',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'POLIKLINIK AL-AMIN',
    subtitletext: 'ALOR GAJAH',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK AL-AMIN',
    address: 'Address',
    clinicaddress: 'KM 16-1, JALAN JELATANG 1, PUSTA PERNIAGAAN JELATANG',
    location: 'Location',
    cliniclocation: 'ALOR GAJAH',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'POLIKLINIK DAN SURGERI COSMOPOINT',
    subtitletext: 'MALIM JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DAN SURGERI COSMOPOINT',
    address: 'Address',
    clinicaddress: 'B2-G3 JALAN ABADI 1, BLOK BUNGA RAYA 2 TAMAN MALIM JAYA',
    location: 'Location',
    cliniclocation: 'MALIM JAYA',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'HIDAYAH MEDIC SDN BHD',
    subtitletext: 'KRUBONG',
    clinic: 'Clinic Name',
    clinicname: 'HIDAYAH MEDIC SDN BHD',
    address: 'Address',
    clinicaddress: 'NO 91 91 1 JALAN SATU KRUBONG TAMAN SATU KRUBONG',
    location: 'Location',
    cliniclocation: 'KRUBONG',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'POLIKLINIK HIDAYAH -BATU BERENDAM',
    subtitletext: 'MELAKA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK HIDAYAH -BATU BERENDAM',
    address: 'Address',
    clinicaddress: 'NO.40 JALAN MUTIARA MELAKA 2 ,MUTIARA MELAKA',
    location: 'Location',
    cliniclocation: 'MELAKA',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK DR.JEGGAN SDN BHD',
    subtitletext: 'DURIAN TUNGGAL',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.JEGGAN SDN BHD',
    address: 'Address',
    clinicaddress: 'DT 685 LORONG DESA 2 TAMAN DESA IDAMAN',
    location: 'Location',
    cliniclocation: 'DURIAN TUNGGAL',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK DR ANI',
    subtitletext: 'AYER KEROH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR ANI',
    address: 'Address',
    clinicaddress: '50, JALAN LINGKARAN MITC, KOMPLEKS PERNIAGAAN MITC,',
    location: 'Location',
    cliniclocation: 'AYER KEROH',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'POLIKLINIK AZHALI MEDIK',
    subtitletext: 'BACHANG',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK AZHALI MEDIK',
    address: 'Address',
    clinicaddress: 'NO.7, JALAN BU5, TAMAN BACHANG UTAMA',
    location: 'Location',
    cliniclocation: 'BACHANG',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK KELUARGA ONE MEDIC - BUKIT BERUANG',
    subtitletext: 'BUKIT BERUANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGA ONE MEDIC - BUKIT BERUANG',
    address: 'Address',
    clinicaddress: 'NO.49, JALAN BUKIT BERUANG UTAMA 2, TAMAN BUKIT BERUANG UTAMA',
    location: 'Location',
    cliniclocation: 'BUKIT BERUANG',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK KELUARGA ONE MEDIC - BACHANG',
    subtitletext: 'MELAKA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGA ONE MEDIC - BACHANG',
    address: 'Address',
    clinicaddress: 'C04, RUMAH PANGSA BACHANG PERMAI, JALAN TUN FATIMAH,',
    location: 'Location',
    cliniclocation: 'MELAKA',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK KELUARGA ONE MEDIC - TANGGA BATU',
    subtitletext: 'TANGGA BATU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGA ONE MEDIC - TANGGA BATU',
    address: 'Address',
    clinicaddress: 'NO.38 & 40, JALAN LEMBING 1 & 3, TAMAN TANGGA BATU PERMAI',
    location: 'Location',
    cliniclocation: 'TANGGA BATU',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK KELUARGA ONE MEDIC - ALOR GAJAH',
    subtitletext: 'ALOR GAJAH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGA ONE MEDIC - ALOR GAJAH',
    address: 'Address',
    clinicaddress: 'KM 11, TAMAN JAYA',
    location: 'Location',
    cliniclocation: 'ALOR GAJAH',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK KELUARGA ONE MEDIC - JASIN',
    subtitletext: 'JASIN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGA ONE MEDIC - JASIN',
    address: 'Address',
    clinicaddress: 'JA9949-G, BANDAR BARU JASIN 3,',
    location: 'Location',
    cliniclocation: 'JASIN',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
    Msclist(
    titletext: 'KLINIK IMPIAN - DURIAN TUNGGAL',
    subtitletext: 'DURIAN TUNGGAL',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK IMPIAN - DURIAN TUNGGAL',
    address: 'Address',
    clinicaddress: 'N0 90 TINGKAT BAWAH JALAN ST PERMAI 2 TAMAN SERI TUAH PERMAI',
    location: 'Location',
    cliniclocation: 'DURIAN TUNGGAL',
    state: 'State',
    nameofstate: 'MELAKA',
    ),
];