import 'package:flutter/material.dart';

class Nssclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Nssclist({
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
  });
}

final NegeriSembilanStateClinicList = [
  Nssclist(
    titletext: 'KLINIK SITI - NILAI',
    subtitletext: 'NILAI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - NILAI',
    address: 'Address',
    clinicaddress:
        'NO.5, JALAN SETIA TROPIKA 1/28, TAMAN SETIA TROPIKA, KEMPAS',
    location: 'Location',
    cliniclocation: 'NILAI',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'MEGAKLINIK ZAHRAN BANDAR BARU NILAI',
    subtitletext: 'NILAI',
    clinic: 'Clinic Name',
    clinicname: 'MEGAKLINIK ZAHRAN BANDAR BARU NILAI',
    address: 'Address',
    clinicaddress:
        'PT9907 & PT9908 ( TINGKAT BAWAH) ,JALAN BBN 1/3G,PUSAT BANDAR PUTRA POINT',
    location: 'Location',
    cliniclocation: 'NILAI',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK DR CHAN',
    subtitletext: 'NILAI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR CHAN',
    address: 'Address',
    clinicaddress: 'PT 4697, JALAN TS 1/1, TAMAN SEMARAK',
    location: 'Location',
    cliniclocation: 'NILAI',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK AISYAH DAN YUSOF',
    subtitletext: 'NILAI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK AISYAH DAN YUSOF',
    address: 'Address',
    clinicaddress:
        'NO. B25, JALAN PUSAT NIAGA KLIA 2, KLIA BUSINESS CENTRE, KUARTERS KLIA',
    location: 'Location',
    cliniclocation: 'NILAI',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'POLIKLINIK DAMAI 24 JAM',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DAMAI 24 JAM',
    address: 'Address',
    clinicaddress: 'NO 82-G ,JALAN BPS5, BANDAR PRIMA SENAWANG',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'POLIKLINIK KELUARGA',
    subtitletext: 'LUKUT',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK KELUARGA',
    address: 'Address',
    clinicaddress: 'NO 4321 TAMAN SENTOSA , BATU 3 1/2 JALAN SEREMBAN',
    location: 'Location',
    cliniclocation: 'LUKUT',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'POLIKLINIK MUC',
    subtitletext: 'LABU',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK MUC',
    address: 'Address',
    clinicaddress: '3, WISMA KOPERASI LABU, JALAN KOPERASI LABU 1',
    location: 'Location',
    cliniclocation: 'LABU',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK HANAFI - SEREMBAN 2',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK HANAFI - SEREMBAN 2',
    address: 'Address',
    clinicaddress:
        'NO.84 (TINGKAT BAWAH), JALAN S2 B19, PUSAT DAGANGAN CENTRIO SEREMBAN 2',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK MEDIVIRON - SEREMBAN 2',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIVIRON - SEREMBAN 2',
    address: 'Address',
    clinicaddress: 'NO.18G, JALAN S2 B18, BIZ AVENUE SEREMBAN 2',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK MEDIVIRON - SEREMBAN',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIVIRON - SEREMBAN',
    address: 'Address',
    clinicaddress: 'LOT 3255 GF, JALAN DATO SHEIKH AHMAD',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK FAMILI',
    subtitletext: 'MANTIN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAMILI',
    address: 'Address',
    clinicaddress: 'NO.1-G JALAN BESAR MANTIN',
    location: 'Location',
    cliniclocation: 'MANTIN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK PERGIGIAN HELMY',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PERGIGIAN HELMY',
    address: 'Address',
    clinicaddress: 'NO.25A, LORONG SRI MAWAR 12/2 SRI MAWAR FASA 2 SENAWANG',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK MEDISINA - BANDAR SRI SENDAYAN',
    subtitletext: 'BANDAR SRI SENDAYAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDISINA - BANDAR SRI SENDAYAN',
    address: 'Address',
    clinicaddress: 'NO.1767 (GROUND FLOOR), JALAN NUSARI BAYU 7/1, NUSARI BIZ',
    location: 'Location',
    cliniclocation: 'BANDAR SRI SENDAYAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK MEDISINA - SEREMBAN 2',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDISINA - SEREMBAN 2',
    address: 'Address',
    clinicaddress: 'NO.53 (GF) , JALAN S2 B18 , PUSAT DAGANGAN SEREMBAN 2',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK CHUA - GEMENCHEH',
    subtitletext: 'GEMENCHEH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CHUA - GEMENCHEH',
    address: 'Address',
    clinicaddress: 'NO.6715, PEKAN GEMENCHEH BARU',
    location: 'Location',
    cliniclocation: 'GEMENCHEH',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KELINIK JALAN TEMPLER SDN.BHD.',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'KELINIK JALAN TEMPLER SDN.BHD.',
    address: 'Address',
    clinicaddress: '18 JALAN TUN DR ISMAIL',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'SIBURAN DENTAL SDN BHD',
    subtitletext: 'KUCHING',
    clinic: 'Clinic Name',
    clinicname: 'SIBURAN DENTAL SDN BHD',
    address: 'Address',
    clinicaddress: '1 ST FLOOR,LOT 954,SIBURAN TD(S/L 31)31 GOLDEN SQUARE ,17TH MILE KUCHING/SERIAN ROAD',
    location: 'Location',
    cliniclocation: 'KUCHING',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK SAFURA',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SAFURA',
    address: 'Address',
    clinicaddress: 'NO.75, (GF) JALAN CASURINA 1, TAMAN CASURINA',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
  Nssclist(
    titletext: 'KLINIK NASHRAH',
    subtitletext: 'GEMAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK NASHRAH',
    address: 'Address',
    clinicaddress: '4735, TAMAN PASIR BESAR',
    location: 'Location',
    cliniclocation: 'GEMAS',
    state: 'State',
    nameofstate: 'NEGERI SEMBILAN',
  ),
];
