import 'package:flutter/material.dart';

class Pesclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Pesclist(
    {
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
    }
  );
}
final PerakStateClinicList=[
  Pesclist(
    titletext: 'KLINIK SAFIYA',
    subtitletext: 'TAIPING',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SAFIYA',
    address: 'Address',
    clinicaddress: 'NO.236, JALAN KAMUNTING',
    location: 'Location',
    cliniclocation: 'TAIPING',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK SAMUDERA SITIAWAN',
    subtitletext: 'SITIAWAN',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SAMUDERA SITIAWAN',
    address: 'Address',
    clinicaddress: 'NO.12, TAMAN SITIAWAN MAJU 2',
    location: 'Location',
    cliniclocation: 'SITIAWAN',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK HARMONI',
    subtitletext: 'ULU KINTA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK HARMONI',
    address: 'Address',
    clinicaddress: 'NO.91, DATARAN PERPADUAN 1, TAMAN BERCHAM RAYA, ULU KINTA',
    location: 'Location',
    cliniclocation: 'ULU KINTA',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK PUTRA',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK PUTRA',
    address: 'Address',
    clinicaddress: 'NO.3, MEDAN PUTRA 1, BANDAR BARU PUTRA',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK SHATIN',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SHATIN',
    address: 'Address',
    clinicaddress: '79, JALAN PENGKALAN BARAT, OFF JALAN NEW PASIR PUTEH',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'FAMILY KLINIK',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'FAMILY KLINIK',
    address: 'Address',
    clinicaddress: '16, JALAN PENGKALAN BARAT 23, PENGKALAN GERBANG MUTIARA',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'GUL MEDICAL CENTRE SDN BHD',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'GUL MEDICAL CENTRE SDN BHD',
    address: 'Address',
    clinicaddress: 'NO.38, LEBUH MEDAN IPOH, BANDAR BARU MEDAN',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'MEDIKLINIK KELUARGA',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'MEDIKLINIK KELUARGA',
    address: 'Address',
    clinicaddress: 'NO.81, JALAN WIRA JAYA, TAMAN IPOH JAYA TIMUR 1',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK RAJU',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAJU',
    address: 'Address',
    clinicaddress: 'NO.48, LALUAN TAWAS DAMAI, ANJUNG TAWAS IMPIANA, JALAN KUALA KANGSAR',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK TAN LEE & CHEONG',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK TAN LEE & CHEONG',
    address: 'Address',
    clinicaddress: '41, JALAN BIJEH TIMAH',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK MINDER',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK MINDER',
    address: 'Address',
    clinicaddress: 'NO.47, JALAN PERAJURIT, IPOH GARDEN EAST',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK BAKTI & KLINIK KULIT R.M.',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK BAKTI & KLINIK KULIT R.M.',
    address: 'Address',
    clinicaddress: '70, JALAN TUN ABDUL RAZAK',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'BERCHAAM MEDICAL CLINIC',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'BERCHAAM MEDICAL CLINIC',
    address: 'Address',
    clinicaddress: 'NO.10, PERSIARAN MEDAN BERCHAM 6, PUSAT BANDAR BARU BERCHAM,',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK PENGKALAN (M) SDN BHD',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK PENGKALAN (M) SDN BHD',
    address: 'Address',
    clinicaddress: 'NO.78, HALA PENGKALAN TIMUR SATU, TAMAN PASIR PUTEH SELATAN',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK & DISPENSARI SHARIL',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK & DISPENSARI SHARIL',
    address: 'Address',
    clinicaddress: '37, JALAN DATO MAHARAJALELA',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK MEDIONE 24 JAM ( CAWANGAN TASEK)',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIONE 24 JAM ( CAWANGAN TASEK)',
    address: 'Address',
    clinicaddress: 'NO 43 & 45 ,LALUAN TAWAS DAMAI ,TAMAN TAWAS IDAMAN',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK SEKELUARGA IPOH SDN BHD',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SEKELUARGA IPOH SDN BHD',
    address: 'Address',
    clinicaddress: '44C JALAN KAMARUDDIN ISA,FAIR PARK',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK I-MEDIC',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK I-MEDIC',
    address: 'Address',
    clinicaddress: 'NO 27 SELASAR ROKAM 11, TAMAN IPOH JAYA',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK BALBIR',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK BALBIR',
    address: 'Address',
    clinicaddress: 'NO .2N JALAN BESAR,MENGLEMBU',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'CHEAH & LIM MEDICAL ASSOCIATES SDN BHD',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'CHEAH & LIM MEDICAL ASSOCIATES SDN BHD',
    address: 'Address',
    clinicaddress: '106, JALAN RAJA MUSA AZIZ',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK KRISHNA',
    subtitletext: 'TAIPING',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KRISHNA',
    address: 'Address',
    clinicaddress: '69, JALAN TAMING SARI',
    location: 'Location',
    cliniclocation: 'TAIPING',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK EDINA',
    subtitletext: 'SIMPANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK EDINA',
    address: 'Address',
    clinicaddress: 'NO.39, PULAI BUSINESS CENTRE, SIMPANG PULAI',
    location: 'Location',
    cliniclocation: 'SIMPANG',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'CLINIC KOTA JAYA',
    subtitletext: 'TAIPING',
    clinic: 'Clinic Name',
    clinicname: 'CLINIC KOTA JAYA',
    address: 'Address',
    clinicaddress: 'NO.486, TAMAN KOTA JAYA, SIMPANG',
    location: 'Location',
    cliniclocation: 'TAIPING',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK MUHIBAH',
    subtitletext: 'SUNGAI SIPUT',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MUHIBAH',
    address: 'Address',
    clinicaddress: '43, SRI TAMAN',
    location: 'Location',
    cliniclocation: 'SUNGAI SIPUT',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK DAN SURGERI GUL',
    subtitletext: 'CHEMOR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DAN SURGERI GUL',
    address: 'Address',
    clinicaddress: 'NO.12, LALUAN KLEBANG RESTU 2, MEDAN KLEBANG RETSU',
    location: 'Location',
    cliniclocation: 'CHEMOR',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'H CLINIC SDN BHD',
    subtitletext: 'TAIPING',
    clinic: 'Clinic Name',
    clinicname: 'H CLINIC SDN BHD',
    address: 'Address',
    clinicaddress: 'NO.24, JALAN SULTAN ABDULLAH (EASTERN ROAD)',
    location: 'Location',
    cliniclocation: 'TAIPING',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'H CLINIC SDN BHD - KOTA JAYA',
    subtitletext: 'SIMPANG',
    clinic: 'Clinic Name',
    clinicname: 'H CLINIC SDN BHD - KOTA JAYA',
    address: 'Address',
    clinicaddress: '568, JALAN TAMAN KOTA JAYA',
    location: 'Location',
    cliniclocation: 'SIMPANG',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK KELUARGAKU - SERI MANJUNG',
    subtitletext: 'SERI MANJONG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGAKU - SERI MANJUNG',
    address: 'Address',
    clinicaddress: 'NO.D6, FASA ICI',
    location: 'Location',
    cliniclocation: 'SERI MANJONG',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK LANGKAP MEDICINA',
    subtitletext: 'LANGKAP',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK LANGKAP MEDICINA',
    address: 'Address',
    clinicaddress: 'NO.11 & 13 TINGKAT BAWAH, LORONG INTAN JAYA 1,',
    location: 'Location',
    cliniclocation: 'LANGKAP',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK SUGU',
    subtitletext: 'CHEMOR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SUGU',
    address: 'Address',
    clinicaddress: 'NO.25, LALUAN KLEBANG 21, TAMAN KLEBANG PERDANA',
    location: 'Location',
    cliniclocation: 'CHEMOR',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK M.KUMAR',
    subtitletext: 'SUNGAI SIPUT',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK M.KUMAR',
    address: 'Address',
    clinicaddress: '9, TAMAN LINTANG',
    location: 'Location',
    cliniclocation: 'SUNGAI SIPUT',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'CHUA KELINIK',
    subtitletext: 'SITIAWAN',
    clinic: 'Clinic Name',
    clinicname: 'CHUA KELINIK',
    address: 'Address',
    clinicaddress: '34A, JALAN RAJA OMAR',
    location: 'Location',
    cliniclocation: 'SITIAWAN',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK KHAW',
    subtitletext: 'TAIPING',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KHAW',
    address: 'Address',
    clinicaddress: '35, JALAN MASJID',
    location: 'Location',
    cliniclocation: 'TAIPING',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK NGO',
    subtitletext: 'PANTAI REMIS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK NGO',
    address: 'Address',
    clinicaddress: 'LOT 2680, JALAN BESAR',
    location: 'Location',
    cliniclocation: 'PANTAI REMIS',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK SAMUDERA',
    subtitletext: 'AYER TAWAR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SAMUDERA',
    address: 'Address',
    clinicaddress: 'NO 90 MAIN ROAD',
    location: 'Location',
    cliniclocation: 'AYER TAWAR',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK SUPPAYAH 24 JAM ( TANJONG RAMBUTAN)',
    subtitletext: 'TANJONG RAMBUTAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SUPPAYAH 24 JAM ( TANJONG RAMBUTAN)',
    address: 'Address',
    clinicaddress: 'NO 5 JALAN SATU ,TAMAN CHONG KWEE',
    location: 'Location',
    cliniclocation: 'TANJONG RAMBUTAN',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK RAKYAT- THEATRE STREET',
    subtitletext: 'BIDOR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAKYAT- THEATRE STREET',
    address: 'Address',
    clinicaddress: '20 ,THEATRE STREET',
    location: 'Location',
    cliniclocation: 'BIDOR',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK SALEHUDIN SDN BHD',
    subtitletext: 'TANJONG MALIM',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SALEHUDIN SDN BHD',
    address: 'Address',
    clinicaddress: 'NO 8 JALAN BERNAM,TAMAN BERNAM BARU',
    location: 'Location',
    cliniclocation: 'TANJONG MALIM',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK DR.NAJIHA',
    subtitletext: 'BOTA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.NAJIHA',
    address: 'Address',
    clinicaddress: 'NO.1 JALAN BESAR ,PEKAN BOTA KANAN',
    location: 'Location',
    cliniclocation: 'BOTA',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK RAJEN',
    subtitletext: 'AYER TAWAR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK RAJEN',
    address: 'Address',
    clinicaddress: 'NO 180 JALAN BESAR',
    location: 'Location',
    cliniclocation: 'AYER TAWAR',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK DR DANIEL',
    subtitletext: 'SEREMBAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR DANIEL',
    address: 'Address',
    clinicaddress: 'NO.8 GROUND FLOOR JALAN MPK 1,MEDAN PERDAGANGAN KEPAYANG',
    location: 'Location',
    cliniclocation: 'SEREMBAN',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK HIDAYAH KAMUNTING',
    subtitletext: 'KAMUNTING',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK HIDAYAH KAMUNTING',
    address: 'Address',
    clinicaddress: 'NO.18 JALAN MKJ/1 ,MEDAN KAMUNTING JAYA',
    location: 'Location',
    cliniclocation: 'KAMUNTING',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'KLINIK DAN SURGERI LEE',
    subtitletext: 'SITIAWAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DAN SURGERI LEE',
    address: 'Address',
    clinicaddress: 'NO.53, MAIN ROAD, KAMPONG KOH',
    location: 'Location',
    cliniclocation: 'SITIAWAN',
    state: 'State',
    nameofstate: 'PERAK',
    ),
    Pesclist(
    titletext: 'POLIKLINIK KUMARI',
    subtitletext: 'PARIT BUNTAR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK KUMARI',
    address: 'Address',
    clinicaddress: 'NO.11, JALAN MAHARAJA 1, PUSAT BANDAR,',
    location: 'Location',
    cliniclocation: 'PARIT BUNTAR',
    state: 'State',
    nameofstate: 'PERAK',
    ),
];