import 'package:flutter/material.dart';

class Ssclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Ssclist(
    {
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
    }
  );
}
final SabahStateClinicList=[
  Ssclist(
    titletext: 'PERMAI POLYCLINICS BANDARAN BERJAYA',
    subtitletext: 'KOTA KINABALU',
    clinic: 'Clinic Name',
    clinicname: 'PERMAI POLYCLINICS BANDARAN BERJAYA',
    address: 'Address',
    clinicaddress: 'NO.53 GROUND FLOOR , BANDARAN BERJAYA ,JALAN BERJAYA 5',
    location: 'Location',
    cliniclocation: 'KOTA KINABALU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'PUTATAN KLINIK DAN SURGERI',
    subtitletext: 'KOTA KINABALU',
    clinic: 'Clinic Name',
    clinicname: 'PUTATAN KLINIK DAN SURGERI',
    address: 'Address',
    clinicaddress: 'LOT 5, GROUND FLOOR, MILE 7, PUTATAN LIGHT INDUSTRIES',
    location: 'Location',
    cliniclocation: 'KOTA KINABALU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'POLYCLINIC KINGFISHER',
    subtitletext: 'KOTA KINABALU',
    clinic: 'Clinic Name',
    clinicname: 'POLYCLINIC KINGFISHER',
    address: 'Address',
    clinicaddress: '29, LORONG PLAZA KINGFISHER 3, KINGFISHER PARK',
    location: 'Location',
    cliniclocation: 'KOTA KINABALU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK TUARAN',
    subtitletext: 'TUARAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK TUARAN',
    address: 'Address',
    clinicaddress: 'LOT 1,GROUND FLOOR , BERUNGIS COMMERCIAL CENTRE',
    location: 'Location',
    cliniclocation: 'TUARAN',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'PMG MEDICAL CLINIC',
    subtitletext: 'SIBU',
    clinic: 'Clinic Name',
    clinicname: 'PMG MEDICAL CLINIC',
    address: 'Address',
    clinicaddress: 'LOT 8583,NO 16,G/F,LORONG ULU OYA 11A',
    location: 'Location',
    cliniclocation: 'SIBU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'HS MEDICLINIC AND SURGERY SDN BHD',
    subtitletext: 'KOTA KINABALU',
    clinic: 'Clinic Name',
    clinicname: 'HS MEDICLINIC AND SURGERY SDN BHD',
    address: 'Address',
    clinicaddress: 'LOT L1.15 1ST FLOOR , PLAZA SHELL , 29 JALAN TUANKU ABDUL RAHMAN',
    location: 'Location',
    cliniclocation: 'KOTA KINABALU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: "DOCTOR LAW'S CLINIC",
    subtitletext: 'SARIKEI',
    clinic: 'Clinic Name',
    clinicname: "DOCTOR LAW'S CLINIC",
    address: 'Address',
    clinicaddress: 'NO.33 JALAN HAJI KARIM',
    location: 'Location',
    cliniclocation: 'SARIKEI',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'LEE CLINIC',
    subtitletext: 'MIRI',
    clinic: 'Clinic Name',
    clinicname: 'LEE CLINIC',
    address: 'Address',
    clinicaddress: 'LOT 1291,GROUND FLOOR ,MIRI CENTRE POINT,JALAN MELAYU ,P.O . BOX 746',
    location: 'Location',
    cliniclocation: 'MIRI',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'I-BORNEO KLINIK & SURGERI( BANDAR SIERRA)',
    subtitletext: 'KOTA KINABALU',
    clinic: 'Clinic Name',
    clinicname: 'I-BORNEO KLINIK & SURGERI( BANDAR SIERRA)',
    address: 'Address',
    clinicaddress: 'LOT 1 , BLOCK A SIERRA BIZ HUB',
    location: 'Location',
    cliniclocation: 'KOTA KINABALU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: "DR.CHENG'S MEDICAL CLINIC",
    subtitletext: 'SARIKEI',
    clinic: 'Clinic Name',
    clinicname: "DR.CHENG'S MEDICAL CLINIC",
    address: 'Address',
    clinicaddress: 'NO.60 G/F JALAN BERJAYA',
    location: 'Location',
    cliniclocation: 'SARIKEI',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'SIBURAN UNION CLINIC',
    subtitletext: 'KUCHING',
    clinic: 'Clinic Name',
    clinicname: 'SIBURAN UNION CLINIC',
    address: 'Address',
    clinicaddress: '62,SIBURAN BAZAAR 17 TH MILE KUCHING SERIAN ROAD',
    location: 'Location',
    cliniclocation: 'KUCHING',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK YEE',
    subtitletext: 'MIRI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK YEE',
    address: 'Address',
    clinicaddress: 'NO.2 RIVER ROAD P.O.BOX 1423',
    location: 'Location',
    cliniclocation: 'MIRI',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK KHAIRA',
    subtitletext: 'KUCHING',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KHAIRA',
    address: 'Address',
    clinicaddress: 'NO.236 LOT 2685 JALAN PERMATA TWIN TOWER CENTRE OFF 2 1/2 MILE ROCK ROAD',
    location: 'Location',
    cliniclocation: 'KUCHING',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK FAMILI SABINDO',
    subtitletext: 'TAWAU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAMILI SABINDO',
    address: 'Address',
    clinicaddress: 'LOT 1,BLOK 1 TB 416 JALAN SABINDO 3,BANDAR SABINDO',
    location: 'Location',
    cliniclocation: 'TAWAU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK FAMILI KOMPLEKS TANJUNG',
    subtitletext: 'TAWAU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAMILI KOMPLEKS TANJUNG',
    address: 'Address',
    clinicaddress: 'MPT 4119 TINGKAT 1, KOMPLEKS TANJUNG JALAN DOMINIC',
    location: 'Location',
    cliniclocation: 'TAWAU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK FAMILI GAYA',
    subtitletext: 'TAWAU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAMILI GAYA',
    address: 'Address',
    clinicaddress: 'TB 17894 GROUND FLOOR ,GAYA COMMERCIAL COMPLEX MILE 2 JALAN KUHARA',
    location: 'Location',
    cliniclocation: 'TAWAU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK FAMILI ARENA',
    subtitletext: 'TAWAU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAMILI ARENA',
    address: 'Address',
    clinicaddress: 'NO 4 ,LOT 4A ,PUSAT KOMERSIAL BDC KM 5 JALAN DATUK CHONG THIEN VUN',
    location: 'Location',
    cliniclocation: 'TAWAU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK FAMILI - KOMPLEKS K FAJAR',
    subtitletext: 'TAWAU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAMILI - KOMPLEKS K FAJAR',
    address: 'Address',
    clinicaddress: 'TB 316 BLOK 37 TINGKAT BAWAH KOMPLEKS KOMERSIAL FAJAR',
    location: 'Location',
    cliniclocation: 'TAWAU',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'UNION CLINIC - TABUAN JAYA',
    subtitletext: 'KUCHING',
    clinic: 'Clinic Name',
    clinicname: 'UNION CLINIC - TABUAN JAYA',
    address: 'Address',
    clinicaddress: '893 TABUAN JAYA COMMERCIAL CENTRE JALAN WAN ALWI',
    location: 'Location',
    cliniclocation: 'KUCHING',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: "FAMILY CARE CLINIC DR VICTOR D'CRUZ",
    subtitletext: 'INANAM',
    clinic: 'Clinic Name',
    clinicname: "FAMILY CARE CLINIC DR VICTOR D'CRUZ",
    address: 'Address',
    clinicaddress: 'LOT 51, GF, BLOCK C, INANAM COMMERCIAL CENTRE, PHASE 1, INANAM BARU, JALAN TUARAN, INANAM',
    location: 'Location',
    cliniclocation: 'INANAM',
    state: 'State',
    nameofstate: 'SABAH',
    ),
    Ssclist(
    titletext: 'KLINIK DR MUSTAFA & SURGERI',
    subtitletext: 'LIKAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR MUSTAFA & SURGERI',
    address: 'Address',
    clinicaddress: 'LOT.18, GF, LORONG JUTA 1, JUTA PLAZA LIKAS, JALAN TUARAN',
    location: 'Location',
    cliniclocation: 'LIKAS',
    state: 'State',
    nameofstate: 'SABAH',
    ),
];