import 'package:flutter/material.dart';

class Sasclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Sasclist(
    {
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
    }
  );
}
final SarawakStateClinicList=[
  Sasclist(
    titletext: 'KLINIK MEDAN SENTRAL SDN BHD',
    subtitletext: 'BINTULU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDAN SENTRAL SDN BHD',
    address: 'Address',
    clinicaddress: 'NO.236, ASSYAKIRIN COMMERCE SQUARE PHASE 2, JALAN SULTAN ISKANDAR',
    location: 'Location',
    cliniclocation: 'BINTULU',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK PERGIGIAN KUAN',
    subtitletext: 'IPOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PERGIGIAN KUAN',
    address: 'Address',
    clinicaddress: '38 & 38A ,LORONG TAMAN IPOH SATU ,TAMAN IPOH SELATAN',
    location: 'Location',
    cliniclocation: 'IPOH',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK DR.YONG',
    subtitletext: 'BINTULU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.YONG',
    address: 'Address',
    clinicaddress: '24 BDA SHAHIDA COMMERCIAL CENTRE,P.O. BOX 70',
    location: 'Location',
    cliniclocation: 'BINTULU',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'UNION CLINIC',
    subtitletext: 'BAU',
    clinic: 'Clinic Name',
    clinicname: 'UNION CLINIC',
    address: 'Address',
    clinicaddress: 'NO. 52 JALAN TEMENGGONG SALAU',
    location: 'Location',
    cliniclocation: 'BAU',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK RAJADURAI SDN BHD',
    subtitletext: 'SANDAKAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAJADURAI SDN BHD',
    address: 'Address',
    clinicaddress: 'LOT 4,BLOK 1,BANDRA INDAH,BATU 4,JALAN UTARA',
    location: 'Location',
    cliniclocation: 'SANDAKAN',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK S.K.LO SDN BHD',
    subtitletext: 'TAWAU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK S.K.LO SDN BHD',
    address: 'Address',
    clinicaddress: '1 ST FLOOR ,310 BLOCK 36 FAJAR COMPLEX ,P.O.BOX 803',
    location: 'Location',
    cliniclocation: 'TAWAU',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK SRI TUNKU',
    subtitletext: 'MIRI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SRI TUNKU',
    address: 'Address',
    clinicaddress: 'LOT 11211,GROUND FLOOR ,BLOCK 5,LAMBIR LAND DISTRICT ,PALM VILLA COMMERCIAL CENTRE',
    location: 'Location',
    cliniclocation: 'MIRI',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'SKYLINE MEDICAL CLINIC AND SURGERY',
    subtitletext: 'PENAMPANG',
    clinic: 'Clinic Name',
    clinicname: 'SKYLINE MEDICAL CLINIC AND SURGERY',
    address: 'Address',
    clinicaddress: 'NO 69 GRD FLR BUNDUSAN SQUARE',
    location: 'Location',
    cliniclocation: 'PENAMPANG',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'ONYX HEALTHCARE CLINIC SDN BHD',
    subtitletext: 'PUTATAN',
    clinic: 'Clinic Name',
    clinicname: 'ONYX HEALTHCARE CLINIC SDN BHD',
    address: 'Address',
    clinicaddress: 'LOT 3,GROUND FLOOR ,SILVERGATE PLAZA',
    location: 'Location',
    cliniclocation: 'PUTATAN',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'DR AI LING MEDIC CARE CLINIC',
    subtitletext: 'KUCHING',
    clinic: 'Clinic Name',
    clinicname: 'DR AI LING MEDIC CARE CLINIC',
    address: 'Address',
    clinicaddress: 'LOT 285 GROUND FLOOR ,SECTION 47 ,JALAN BAN HOCK',
    location: 'Location',
    cliniclocation: 'KUCHING',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK DOKTOR WONG',
    subtitletext: 'SARIKEI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DOKTOR WONG',
    address: 'Address',
    clinicaddress: 'LOT 47,JALAN MASJID LAMA',
    location: 'Location',
    cliniclocation: 'SARIKEI',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK HERMAN LOI',
    subtitletext: 'SIBU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK HERMAN LOI',
    address: 'Address',
    clinicaddress: '27 JALAN PEDADA',
    location: 'Location',
    cliniclocation: 'SIBU',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK PERUBATAN KHAIRA',
    subtitletext: 'KUCHING',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PERUBATAN KHAIRA',
    address: 'Address',
    clinicaddress: 'CD 102,BATU KAWAH NEW TOWNSHIP,JALAN BATU KAWAH',
    location: 'Location',
    cliniclocation: 'KUCHING',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK TANG',
    subtitletext: 'KUCHING',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK TANG',
    address: 'Address',
    clinicaddress: 'LOT 287 JALAN SATOK ,P.O. BOX 2462',
    location: 'Location',
    cliniclocation: 'KUCHING',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK DR.PRIYA',
    subtitletext: 'TAWAU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.PRIYA',
    address: 'Address',
    clinicaddress: 'LOT A-9 PUSAT KOMERSIL BINTANG KUBOTA,KM5 JALAN DATUK CHONG THIEN VUN',
    location: 'Location',
    cliniclocation: 'TAWAU',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'PMG MEDICAL CLINIC -JLN KELUPU',
    subtitletext: 'BINTANGOR',
    clinic: 'Clinic Name',
    clinicname: 'PMG MEDICAL CLINIC -JLN KELUPU',
    address: 'Address',
    clinicaddress: 'LOT 115,NO.14 G/F BINTANGOR TOWN DISTRICT ,JALAN KELUPU',
    location: 'Location',
    cliniclocation: 'BINTANGOR',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'PMG MEDICAL CLINIC (SARATOK)SDN BHD',
    subtitletext: 'SARATOK',
    clinic: 'Clinic Name',
    clinicname: 'PMG MEDICAL CLINIC (SARATOK)SDN BHD',
    address: 'Address',
    clinicaddress: 'LOT 640,NEW BAZAAR',
    location: 'Location',
    cliniclocation: 'SARATOK',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'PMG MEDICAL CLINIC (SRI AMAN) SDN BHD',
    subtitletext: 'SRI AMAN',
    clinic: 'Clinic Name',
    clinicname: 'PMG MEDICAL CLINIC (SRI AMAN) SDN BHD',
    address: 'Address',
    clinicaddress: 'LOT 1857 &1858 GROUND FLOOR ,JALAN SABU',
    location: 'Location',
    cliniclocation: 'SRI AMAN',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK DR ZULFIKAR',
    subtitletext: 'TUARAN',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR ZULFIKAR',
    address: 'Address',
    clinicaddress: 'LOT 71 GROUND FLOOR WISMA TELIPOK RIA ,JALAN TUARAN',
    location: 'Location',
    cliniclocation: 'TUARAN',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK ABDUL RAHAMAN POZAN',
    subtitletext: 'KUCHING',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK ABDUL RAHAMAN POZAN',
    address: 'Address',
    clinicaddress: 'GROUND FLOOR LOT 410 SEKSYEN 5 ,KUCHING TOWN LAND DISTRICT ,JALAN KULAS',
    location: 'Location',
    cliniclocation: 'KUCHING',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'KLINIK FAMILI JALAN PAYA',
    subtitletext: 'TAWAU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAMILI JALAN PAYA',
    address: 'Address',
    clinicaddress: 'TB 1872 JALAN PAYA OFF JALAN DOMINIC',
    location: 'Location',
    cliniclocation: 'TAWAU',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'PMG MEDICAL CLINIC - JLN SABU',
    subtitletext: 'SRI AMAN',
    clinic: 'Clinic Name',
    clinicname: 'PMG MEDICAL CLINIC - JLN SABU',
    address: 'Address',
    clinicaddress: 'LOT 1858 ,G/F JALAN SABU',
    location: 'Location',
    cliniclocation: 'SRI AMAN',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
    Sasclist(
    titletext: 'PMG MEDICAL CLINIC -BETONG',
    subtitletext: 'BETONG',
    clinic: 'Clinic Name',
    clinicname: 'PMG MEDICAL CLINIC -BETONG',
    address: 'Address',
    clinicaddress: 'LOT 836 N0.11 G/F BETONG TOWN DISTRICT , JALAN LEE KAI TENG',
    location: 'Location',
    cliniclocation: 'BETONG',
    state: 'State',
    nameofstate: 'SARAWAK',
    ),
];