import 'package:flutter/material.dart';

class Sesclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Sesclist(
    {
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
    }
  );
}
final SelangorStateClinicList=[
  Sesclist(
    titletext: 'KLINIK BALA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BALA',
    address: 'Address',
    clinicaddress: 'NO.9-UG, JALAN PJS G/1A PUSAT PERNIAGAAN LAGOON PERDANA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SRI MANJA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SRI MANJA',
    address: 'Address',
    clinicaddress: 'NO 5, JALAN PJS 6 B KAMPUNG LINDUNGAN ,46150 PETALING JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK ALAM MEDIC - PELANGI DAMANSARA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK ALAM MEDIC - PELANGI DAMANSARA',
    address: 'Address',
    clinicaddress: 'BLOCK AG-7, BLOCK A, PUSAT PERDAGANGAN PELANGI DAMANSARA, PJU 6, PERSIARAN SURIAN, PETALING JAYA, SELANGOR',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'DR. AMIR ABBAS - SEA PARK',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'DR. AMIR ABBAS - SEA PARK',
    address: 'Address',
    clinicaddress: 'NO. 19, JALAN 21/12 SEAPARK , PETALING JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'DR AMIR ABBAS-KELANA JAYA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'DR AMIR ABBAS-KELANA JAYA',
    address: 'Address',
    clinicaddress: 'NO 18 JALAN SS 5A/9 ,KELANA JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK KELANA PUTERI /CAW DR AMIR ABBAS SDN BHD)',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELANA PUTERI /CAW DR AMIR ABBAS SDN BHD)',
    address: 'Address',
    clinicaddress: 'NO. 17 GF ,JALAN SS 5B/4, KELANA JAYA ,SELANGOR',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KELINIK NASIONAL',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KELINIK NASIONAL',
    address: 'Address',
    clinicaddress: 'NO.6, SS 3/35, UNIVERSITI GARDEN , 47300 PETALING JAYA ,SELANGOR',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK LINA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK LINA',
    address: 'Address',
    clinicaddress: 'FG-17, BLOCK F, NO. 2A, JALAN PJS 2/1, APARTMENT TAMAN MEDAN JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDI PERDANA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDI PERDANA',
    address: 'Address',
    clinicaddress: 'NO. 8A, JALAN 222, SEKSYEN 51A',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KELINIK NASIONAL',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KELINIK NASIONAL',
    address: 'Address',
    clinicaddress: 'NO. 547B, JALAN 9A/12, SG WAY',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK WU & TANGLIM',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK WU & TANGLIM',
    address: 'Address',
    clinicaddress: '72 JALAN OTHMAN TIMOR',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'SELCARE CLINIC',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'SELCARE CLINIC',
    address: 'Address',
    clinicaddress: 'B-27-1 BLOCK B ,JAYA ONE ,92 JALAN UNIVERSITI ,SECTION 13',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK FERNANDEZ DAN RAKAN RAKAN',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FERNANDEZ DAN RAKAN RAKAN',
    address: 'Address',
    clinicaddress: '615 A ,JALAN BESAR SUNGAI WAY',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI DATO HARUN',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI DATO HARUN',
    address: 'Address',
    clinicaddress: 'NO 3 A-1 JALAN PJS 2/18A ,TAMAN MAJU JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK BUNGA RAYA - KG LINDUNGAN',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BUNGA RAYA - KG LINDUNGAN',
    address: 'Address',
    clinicaddress: '21 JALAN PJS 6/2B ,KG LINDUNGAN',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK RAYYAN',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAYYAN',
    address: 'Address',
    clinicaddress: 'NO 21 JALAN SM 10 ,TAMAN SRI MANJA ,JALAN KLANG LAMA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDILINIK - MENTARI COURT',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINIK - MENTARI COURT',
    address: 'Address',
    clinicaddress: 'PODIUM A,NO CPA-G-06 ,MENTARI COURT APT,JALAN PJS 8/9 TAMAN SRI MENTARI',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDILINK - SECTION 5',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINK - SECTION 5',
    address: 'Address',
    clinicaddress: 'GROUND FLOOR ,TOWER 8 PJ CITY DEVELOPMENT ,15A JALAN 2/9 SECTION 5',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDILINK - USJ 9',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINK - USJ 9',
    address: 'Address',
    clinicaddress: 'NO.19 JALAN USJ 9/3F, UEP SUBANG JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SEPAKAT',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SEPAKAT',
    address: 'Address',
    clinicaddress: 'NO.3 JALAN PJS 6B TAMAN LINDUNGAN PETALING JAYA.',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK ALAM MEDIC - PJ',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK ALAM MEDIC - PJ',
    address: 'Address',
    clinicaddress: 'NO,13-G,BLOCK 13,PJ 21 JALAN SS3/39, PETALING JAYA.',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SP CARE - KOTA DAMANSARA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SP CARE - KOTA DAMANSARA',
    address: 'Address',
    clinicaddress: 'NO. 9-G JALAN PJU 5/20E , KOTA DAMANSARA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK K.Y.LEE',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK K.Y.LEE',
    address: 'Address',
    clinicaddress: 'NO. 8, JALAN CAMAR 4/3 SEKSYEN 4, KOTA DAMANSARA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK DAN SURGERI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DAN SURGERI',
    address: 'Address',
    clinicaddress: 'NO.33, JALAN 19/6, SUBANG JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK BAIDURI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BAIDURI',
    address: 'Address',
    clinicaddress: '21-1,JALAN PJU 8/5D, PERDANA BUSINEES CENTRE,BANDAR DAMANSARA PERDANA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR.ASHRAF HAMID',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.ASHRAF HAMID',
    address: 'Address',
    clinicaddress: 'NO.9 JALAN MJ7, TAMAN MAJU JAYA OFF JALAN KLANG LAMA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'MERITUS MEDICAL CLINIC SDN.BHD',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'MERITUS MEDICAL CLINIC SDN.BHD',
    address: 'Address',
    clinicaddress: 'C-G-05A, CENTUM@ OASIS CORPORATE PARK, OASIS DAMANSARA NO.2, JALAN PJU 1A/2',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK WIDURI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK WIDURI',
    address: 'Address',
    clinicaddress: 'NO.42 JALAN MEDAN 10,TAMAN MEDAN',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK WELLCARE DAMAI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK WELLCARE DAMAI',
    address: 'Address',
    clinicaddress: '0008 GROUND FLOOR VISTA SHOP, JALAN PJU 10/2B DAMANSARA DAMAI',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK BUKIT MAYANG EMAS',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK BUKIT MAYANG EMAS',
    address: 'Address',
    clinicaddress: '32 JALAN BM 1/2, TAMAN BUKIT MAYANG EMAS',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK ROY',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK ROY',
    address: 'Address',
    clinicaddress: 'NO.9-1 JALAN PJU 8/5 I PERDANA BUSINESS CENTRE, BANDAR DAMANSARA PERDANA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DAN SURGERI GUNA - PJ',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DAN SURGERI GUNA - PJ',
    address: 'Address',
    clinicaddress: 'NO.19, GROUND FLOOR, JALAN PJS 10/24, TAMAN SRI SUBANG',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK SRI PRIMA - PJ',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SRI PRIMA - PJ',
    address: 'Address',
    clinicaddress: '592, JALAN SS 8A/14',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI - DAMANSARA DAMAI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - DAMANSARA DAMAI',
    address: 'Address',
    clinicaddress: 'L-010 (GROUND FLOOR), JALAN PJU 10/2A, DAMANSARA DAMAI',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
];