import 'package:flutter/material.dart';

class Sesclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Sesclist(
    {
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
    }
  );
}
final SelangorStateClinicList=[
  Sesclist(
    titletext: 'KLINIK BALA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BALA',
    address: 'Address',
    clinicaddress: 'NO.9-UG, JALAN PJS G/1A PUSAT PERNIAGAAN LAGOON PERDANA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SRI MANJA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SRI MANJA',
    address: 'Address',
    clinicaddress: 'NO 5, JALAN PJS 6 B KAMPUNG LINDUNGAN ,46150 PETALING JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK ALAM MEDIC - PELANGI DAMANSARA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK ALAM MEDIC - PELANGI DAMANSARA',
    address: 'Address',
    clinicaddress: 'BLOCK AG-7, BLOCK A, PUSAT PERDAGANGAN PELANGI DAMANSARA, PJU 6, PERSIARAN SURIAN, PETALING JAYA, SELANGOR',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'DR. AMIR ABBAS - SEA PARK',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'DR. AMIR ABBAS - SEA PARK',
    address: 'Address',
    clinicaddress: 'NO. 19, JALAN 21/12 SEAPARK , PETALING JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'DR AMIR ABBAS-KELANA JAYA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'DR AMIR ABBAS-KELANA JAYA',
    address: 'Address',
    clinicaddress: 'NO 18 JALAN SS 5A/9 ,KELANA JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK KELANA PUTERI /CAW DR AMIR ABBAS SDN BHD)',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELANA PUTERI /CAW DR AMIR ABBAS SDN BHD)',
    address: 'Address',
    clinicaddress: 'NO. 17 GF ,JALAN SS 5B/4, KELANA JAYA ,SELANGOR',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KELINIK NASIONAL',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KELINIK NASIONAL',
    address: 'Address',
    clinicaddress: 'NO.6, SS 3/35, UNIVERSITI GARDEN , 47300 PETALING JAYA ,SELANGOR',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK LINA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK LINA',
    address: 'Address',
    clinicaddress: 'FG-17, BLOCK F, NO. 2A, JALAN PJS 2/1, APARTMENT TAMAN MEDAN JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDI PERDANA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDI PERDANA',
    address: 'Address',
    clinicaddress: 'NO. 8A, JALAN 222, SEKSYEN 51A',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KELINIK NASIONAL',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KELINIK NASIONAL',
    address: 'Address',
    clinicaddress: 'NO. 547B, JALAN 9A/12, SG WAY',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK WU & TANGLIM',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK WU & TANGLIM',
    address: 'Address',
    clinicaddress: '72 JALAN OTHMAN TIMOR',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'SELCARE CLINIC',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'SELCARE CLINIC',
    address: 'Address',
    clinicaddress: 'B-27-1 BLOCK B ,JAYA ONE ,92 JALAN UNIVERSITI ,SECTION 13',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK FERNANDEZ DAN RAKAN RAKAN',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FERNANDEZ DAN RAKAN RAKAN',
    address: 'Address',
    clinicaddress: '615 A ,JALAN BESAR SUNGAI WAY',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI DATO HARUN',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI DATO HARUN',
    address: 'Address',
    clinicaddress: 'NO 3 A-1 JALAN PJS 2/18A ,TAMAN MAJU JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK BUNGA RAYA - KG LINDUNGAN',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BUNGA RAYA - KG LINDUNGAN',
    address: 'Address',
    clinicaddress: '21 JALAN PJS 6/2B ,KG LINDUNGAN',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK RAYYAN',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAYYAN',
    address: 'Address',
    clinicaddress: 'NO 21 JALAN SM 10 ,TAMAN SRI MANJA ,JALAN KLANG LAMA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDILINIK - MENTARI COURT',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINIK - MENTARI COURT',
    address: 'Address',
    clinicaddress: 'PODIUM A,NO CPA-G-06 ,MENTARI COURT APT,JALAN PJS 8/9 TAMAN SRI MENTARI',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDILINK - SECTION 5',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINK - SECTION 5',
    address: 'Address',
    clinicaddress: 'GROUND FLOOR ,TOWER 8 PJ CITY DEVELOPMENT ,15A JALAN 2/9 SECTION 5',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDILINK - USJ 9',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINK - USJ 9',
    address: 'Address',
    clinicaddress: 'NO.19 JALAN USJ 9/3F, UEP SUBANG JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SEPAKAT',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SEPAKAT',
    address: 'Address',
    clinicaddress: 'NO.3 JALAN PJS 6B TAMAN LINDUNGAN PETALING JAYA.',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK ALAM MEDIC - PJ',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK ALAM MEDIC - PJ',
    address: 'Address',
    clinicaddress: 'NO,13-G,BLOCK 13,PJ 21 JALAN SS3/39, PETALING JAYA.',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SP CARE - KOTA DAMANSARA',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SP CARE - KOTA DAMANSARA',
    address: 'Address',
    clinicaddress: 'NO. 9-G JALAN PJU 5/20E , KOTA DAMANSARA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK K.Y.LEE',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK K.Y.LEE',
    address: 'Address',
    clinicaddress: 'NO. 8, JALAN CAMAR 4/3 SEKSYEN 4, KOTA DAMANSARA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK DAN SURGERI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DAN SURGERI',
    address: 'Address',
    clinicaddress: 'NO.33, JALAN 19/6, SUBANG JAYA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK BAIDURI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BAIDURI',
    address: 'Address',
    clinicaddress: '21-1,JALAN PJU 8/5D, PERDANA BUSINEES CENTRE,BANDAR DAMANSARA PERDANA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR.ASHRAF HAMID',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.ASHRAF HAMID',
    address: 'Address',
    clinicaddress: 'NO.9 JALAN MJ7, TAMAN MAJU JAYA OFF JALAN KLANG LAMA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'MERITUS MEDICAL CLINIC SDN.BHD',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'MERITUS MEDICAL CLINIC SDN.BHD',
    address: 'Address',
    clinicaddress: 'C-G-05A, CENTUM@ OASIS CORPORATE PARK, OASIS DAMANSARA NO.2, JALAN PJU 1A/2',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK WIDURI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK WIDURI',
    address: 'Address',
    clinicaddress: 'NO.42 JALAN MEDAN 10,TAMAN MEDAN',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK WELLCARE DAMAI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK WELLCARE DAMAI',
    address: 'Address',
    clinicaddress: '0008 GROUND FLOOR VISTA SHOP, JALAN PJU 10/2B DAMANSARA DAMAI',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK BUKIT MAYANG EMAS',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK BUKIT MAYANG EMAS',
    address: 'Address',
    clinicaddress: '32 JALAN BM 1/2, TAMAN BUKIT MAYANG EMAS',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK ROY',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK ROY',
    address: 'Address',
    clinicaddress: 'NO.9-1 JALAN PJU 8/5 I PERDANA BUSINESS CENTRE, BANDAR DAMANSARA PERDANA',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DAN SURGERI GUNA - PJ',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DAN SURGERI GUNA - PJ',
    address: 'Address',
    clinicaddress: 'NO.19, GROUND FLOOR, JALAN PJS 10/24, TAMAN SRI SUBANG',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK SRI PRIMA - PJ',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SRI PRIMA - PJ',
    address: 'Address',
    clinicaddress: '592, JALAN SS 8A/14',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI - DAMANSARA DAMAI',
    subtitletext: 'PETALING JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - DAMANSARA DAMAI',
    address: 'Address',
    clinicaddress: 'L-010 (GROUND FLOOR), JALAN PJU 10/2A, DAMANSARA DAMAI',
    location: 'Location',
    cliniclocation: 'PETALING JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SIDHU',
    subtitletext: 'BATU CAVES',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SIDHU',
    address: 'Address',
    clinicaddress: 'NO.16, JALAN SJ 14, TAMAN SELAYANG JAYA',
    location: 'Location',
    cliniclocation: 'BATU CAVES',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK & SURGERI ELAN',
    subtitletext: 'SHAH ALAM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK & SURGERI ELAN',
    address: 'Address',
    clinicaddress: 'NO.26, JALAN UTAS 15/A, SEKSYEN 15 40200 SHAH ALAM',
    location: 'Location',
    cliniclocation: 'SHAH ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR SHAMSUDDIN',
    subtitletext: 'SUNGAI BULOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR SHAMSUDDIN',
    address: 'Address',
    clinicaddress: 'LOT 2399 JALAN 1A/3, BANDAR BARU SUNGAI BULOH',
    location: 'Location',
    cliniclocation: 'SUNGAI BULOH',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SULAIMAN TALIB SDN BHD',
    subtitletext: 'BATU CAVES',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SULAIMAN TALIB SDN BHD',
    address: 'Address',
    clinicaddress: 'SH-19, JALAN 7, TAMAN GREENWOOD, BATU CAVES, SELANGOR',
    location: 'Location',
    cliniclocation: 'BATU CAVES',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK CYBERMEDIK',
    subtitletext: 'SHAH ALAM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CYBERMEDIK',
    address: 'Address',
    clinicaddress: 'NO. 41, JALAN SUNGA KERANJI Q/32, SEKSYEN 32, KEMUNING GREENVILLE, SHAH ALAM, SELANGOR',
    location: 'Location',
    cliniclocation: 'SHAH ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK PENAWAR - SERDANG',
    subtitletext: 'SERDANG',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK PENAWAR - SERDANG',
    address: 'Address',
    clinicaddress: 'NO. 3344, JALAN 18/32, TAMAN SRI SERDANG, SERI SERDANG, SELANGOR',
    location: 'Location',
    cliniclocation: 'SERDANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK PENAWAR',
    subtitletext: 'SERI KEMBANGAN',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK PENAWAR',
    address: 'Address',
    clinicaddress: 'NO. 3344, JALAN 18/32, TAMAN SRI SERDANG , SERI KEMBANGAN , SELANGOR',
    location: 'Location',
    cliniclocation: 'SERI KEMBANGAN',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK JACOB',
    subtitletext: 'BATANG BERJUNTAI ( BESTARI JAYA)',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK JACOB',
    address: 'Address',
    clinicaddress: 'NO. 52, JALAN BESAR BATANG BERJUNTAI ( BESTARI JAYA ), SELANGOR',
    location: 'Location',
    cliniclocation: 'BATANG BERJUNTAI ( BESTARI JAYA)',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK EASTERN',
    subtitletext: 'SUBANG JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK EASTERN',
    address: 'Address',
    clinicaddress: 'NO. 7, JALAN USJ 2/2C, UEP SUBANG JAYA 47600 SUBANG JAYA , SELANGOR',
    location: 'Location',
    cliniclocation: 'SUBANG JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK ALLIANCE',
    subtitletext: 'PUCHONG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK ALLIANCE',
    address: 'Address',
    clinicaddress: 'NO. 16, JALAN JALAN KENARI 1, BANDAR PUCHONG JAYA, PUCHONG',
    location: 'Location',
    cliniclocation: 'PUCHONG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DHARAN',
    subtitletext: 'BATANG KALI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DHARAN',
    address: 'Address',
    clinicaddress: 'NO. 10-G, JALAN ARA 2, PUSAT PERDAGANGAN ARA, SEKSYEN 5, BANDAR UTAMA',
    location: 'Location',
    cliniclocation: 'BATANG KALI',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR.SITI DAN RAKAN2 - TAMAN PUCHONG PERMAI',
    subtitletext: 'TAMAN PUCHONG PERMAI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.SITI DAN RAKAN2 - TAMAN PUCHONG PERMAI',
    address: 'Address',
    clinicaddress: 'NO. 2, JALAN PUCHONG PERMAI 3, TAMAN PUCHONG PERMAI, BATU 13, PUCHONG, SELANGOR',
    location: 'Location',
    cliniclocation: 'TAMAN PUCHONG PERMAI',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'SHAH ALAM',
    subtitletext: 'TAMAN PUCHONG PERMAI',
    clinic: 'Clinic Name',
    clinicname: 'SHAH ALAM',
    address: 'Address',
    clinicaddress: 'NO. 7-G, JALAN KEMUNING INDAH S 32/5,KEMUNING UTAMA, SEKSYEN 32',
    location: 'Location',
    cliniclocation: 'TAMAN PUCHONG PERMAI',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK KELUARGA BANDAR BOTANIC',
    subtitletext: 'KLANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGA BANDAR BOTANIC',
    address: 'Address',
    clinicaddress: 'NO. 26, JALAN PALMA RAJA 1, BANDAR BOTANIC, KLANG, SELANGOR',
    location: 'Location',
    cliniclocation: 'KLANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK LINGAM',
    subtitletext: 'DENGKIL',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK LINGAM',
    address: 'Address',
    clinicaddress: 'NO. 5, JALAN BESAR , TAMAN DENGKIL',
    location: 'Location',
    cliniclocation: 'DENGKIL',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDIC - HEALTH KOTA DAMANSARA',
    subtitletext: 'KOTA DAMANSARA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIC - HEALTH KOTA DAMANSARA',
    address: 'Address',
    clinicaddress: 'NO. 45-G, JALAN CECAWI 6/33, SEKSYEN 6',
    location: 'Location',
    cliniclocation: 'KOTA DAMANSARA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK NANDA',
    subtitletext: 'KLANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK NANDA',
    address: 'Address',
    clinicaddress: 'NO. 33, JALAN DATO HAMZAH',
    location: 'Location',
    cliniclocation: 'KLANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK NUR RAISHA',
    subtitletext: 'BANDAR PUNCAK ALAM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK NUR RAISHA',
    address: 'Address',
    clinicaddress: 'NO. 20, JALAN NIAGA BESTARI 8, PUNCAK BESTARI',
    location: 'Location',
    cliniclocation: 'BANDAR PUNCAK ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK PUBLIC',
    subtitletext: 'JENJAROM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PUBLIC',
    address: 'Address',
    clinicaddress: 'NO. M-11, JALAN BESAR',
    location: 'Location',
    cliniclocation: 'JENJAROM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SERI MELAWATI SDN BHD',
    subtitletext: 'HULU KELANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SERI MELAWATI SDN BHD',
    address: 'Address',
    clinicaddress: 'NO. 9143, JALAN BANDAR 4, TAMAN MELAWATI',
    location: 'Location',
    cliniclocation: 'HULU KELANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'ARANDA CLINIC',
    subtitletext: 'SHAH ALAM',
    clinic: 'Clinic Name',
    clinicname: 'ARANDA CLINIC',
    address: 'Address',
    clinicaddress: 'NO 35,JALAN DAMAI 25/60 SEKSYEN 25 ,TAMAN SRI MUDA',
    location: 'Location',
    cliniclocation: 'SHAH ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK LIFE CARE',
    subtitletext: 'AMPANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK LIFE CARE',
    address: 'Address',
    clinicaddress: 'NO. 47-G, JALAN WAWASAN AMPANG 2/1, BANDAR BARU AMPANG',
    location: 'Location',
    cliniclocation: 'AMPANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'GOMBAK MEDICARE CLINIC',
    subtitletext: 'BATU CAVES',
    clinic: 'Clinic Name',
    clinicname: 'GOMBAK MEDICARE CLINIC',
    address: 'Address',
    clinicaddress: 'N0. 1 & 3, JALAN SG 3/16, TAMAN SRI GOMBAK',
    location: 'Location',
    cliniclocation: 'BATU CAVES',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK BAHARUDIN',
    subtitletext: 'SHAH ALAM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BAHARUDIN',
    address: 'Address',
    clinicaddress: 'NO. 25 JALAN BUNGA MELOR, SEKSYEN 2',
    location: 'Location',
    cliniclocation: 'SHAH ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR MUIZ',
    subtitletext: 'SUNGAI BULOH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR MUIZ',
    address: 'Address',
    clinicaddress: 'G-1-56 JALAN SP 11/3, SERI PRISTANA',
    location: 'Location',
    cliniclocation: 'SUNGAI BULOH',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR.KIRAN',
    subtitletext: 'SUBANG JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.KIRAN',
    address: 'Address',
    clinicaddress: 'NO 5 JALAN USJ 9/3F ,UEP SUBANG JAYA',
    location: 'Location',
    cliniclocation: 'SUBANG JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK INDREN',
    subtitletext: 'AMPANG',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK INDREN',
    address: 'Address',
    clinicaddress: '55B-G JALAN PANDAN CAHAYA 2/3 ,TAMAN PANDAN CAHAYA',
    location: 'Location',
    cliniclocation: 'AMPANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MAZHALIMI',
    subtitletext: 'AMPANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MAZHALIMI',
    address: 'Address',
    clinicaddress: 'B-G-11, RESIDENSI BISTARIA ,TAMAN UKAY BISTARI',
    location: 'Location',
    cliniclocation: 'AMPANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR.ZETTY',
    subtitletext: 'SUBANG JAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR.ZETTY',
    address: 'Address',
    clinicaddress: 'NO.25 JALAN PUTRA MAHKOTA 7/6C ,PUTRA HEIGHT',
    location: 'Location',
    cliniclocation: 'SUBANG JAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK RAWATAN UTAMA',
    subtitletext: 'CHERAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAWATAN UTAMA',
    address: 'Address',
    clinicaddress: 'NO.22 JALAN CJ 3/13-1 ,TAMAN CHERAS JAYA',
    location: 'Location',
    cliniclocation: 'CHERAS',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEWAH ( SEMENYIH )',
    subtitletext: 'SEMENYIH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEWAH ( SEMENYIH )',
    address: 'Address',
    clinicaddress: '11, JALAN PASAR BARU 2,OFF JALAN SEMENYIH',
    location: 'Location',
    cliniclocation: 'SEMENYIH',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK KELUARGA ROHANI',
    subtitletext: 'KUALA SELANGOR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGA ROHANI',
    address: 'Address',
    clinicaddress: 'NO.38 GROUND FLOOR ,LORONG NALURI SUKAM A 8/A, BANDAR PUNCAK ALAM',
    location: 'Location',
    cliniclocation: 'KUALA SELANGOR',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK VISTA MEDIC',
    subtitletext: 'SEMENYIH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK VISTA MEDIC',
    address: 'Address',
    clinicaddress: '13 A-G JALAN VISTA VALLEY 1, SEMENYIH VISTA VALLEY',
    location: 'Location',
    cliniclocation: 'SEMENYIH',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR NAJWA',
    subtitletext: 'BANDAR BARU BANGI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR NAJWA',
    address: 'Address',
    clinicaddress: 'NO 51-A JALAN 3/69, SEKSYEN 3 TAMBAHAN',
    location: 'Location',
    cliniclocation: 'BANDAR BARU BANGI',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DR NAJWA',
    subtitletext: 'KAJANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR NAJWA',
    address: 'Address',
    clinicaddress: 'LOT 24561 , ARMA SQUARE ,JALAN BESAR, SG MERAB LUAR',
    location: 'Location',
    cliniclocation: 'KAJANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SP CARE',
    subtitletext: 'RAWANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SP CARE',
    address: 'Address',
    clinicaddress: '4 G& 5G JALAN HELIKONIA , SG CHOH',
    location: 'Location',
    cliniclocation: 'RAWANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK DHARAN',
    subtitletext: 'RAWANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DHARAN',
    address: 'Address',
    clinicaddress: 'NO. 83 JALAN BANDAR RAWANG 3, PUSAT BANDAR RAWANG',
    location: 'Location',
    cliniclocation: 'RAWANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'POLIKLINIK SRI MUDA SDN BHD',
    subtitletext: 'SHAH ALAM',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SRI MUDA SDN BHD',
    address: 'Address',
    clinicaddress: 'NO 13 JALAN HIDAYAT 25/85,TAMAN SRI MUDA',
    location: 'Location',
    cliniclocation: 'SHAH ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK FAMILI LEIYA',
    subtitletext: 'SEPANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK FAMILI LEIYA',
    address: 'Address',
    clinicaddress: 'NO.11 JALAN GEMILANG 1, PUSAT PERDAGANGAN GEMILANG',
    location: 'Location',
    cliniclocation: 'SEPANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK ARUL',
    subtitletext: 'TANJONG KARANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK ARUL',
    address: 'Address',
    clinicaddress: '9 LORONG BAHAGIA 2',
    location: 'Location',
    cliniclocation: 'TANJONG KARANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK AMAR - BDR BARU RAWANG',
    subtitletext: 'RAWANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK AMAR - BDR BARU RAWANG',
    address: 'Address',
    clinicaddress: 'NO 59 JALAN BANDAR RAWANG 2,BANDAR BARU RAWANG',
    location: 'Location',
    cliniclocation: 'RAWANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK AMAR - BDR COUNTRY HOMES',
    subtitletext: 'RAWANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK AMAR - BDR COUNTRY HOMES',
    address: 'Address',
    clinicaddress: 'NO 11 JALAN PUSAT BCH 1A , BANDAR COUNTRY HOMES',
    location: 'Location',
    cliniclocation: 'RAWANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'AWAM CLINIC GLENMARIE',
    subtitletext: 'SHAH ALAM',
    clinic: 'Clinic Name',
    clinicname: 'AWAM CLINIC GLENMARIE',
    address: 'Address',
    clinicaddress: 'NO 9 JALAN JURUAUDIT U1/37 GLENMARIE ,SEKSYEN U1',
    location: 'Location',
    cliniclocation: 'SHAH ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK KELANG',
    subtitletext: 'KLANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELANG',
    address: 'Address',
    clinicaddress: '25 JALAN GOH HOCK HUAT',
    location: 'Location',
    cliniclocation: 'KLANG',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK MEDIK PERDANA',
    subtitletext: 'CYBERJAYA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIK PERDANA',
    address: 'Address',
    clinicaddress: '4803-0-1 CBD PERDANA ,JALAN PERDANA ,OFF PERSIARAN MULTIMEDIA',
    location: 'Location',
    cliniclocation: 'CYBERJAYA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI - DENGKIL',
    subtitletext: 'DENGKIL',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - DENGKIL',
    address: 'Address',
    clinicaddress: 'NO 19 GROUND FLOOR JALAN MUTIARA 1 TAMAN MUTIARA',
    location: 'Location',
    cliniclocation: 'DENGKIL',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI -SUNGAI BULOH',
    subtitletext: 'SHAH ALAM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI -SUNGAI BULOH',
    address: 'Address',
    clinicaddress: 'NO 61 -G JALAN NAUTIKA A U20/A',
    location: 'Location',
    cliniclocation: 'SHAH ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI - BSP',
    subtitletext: 'JENJAROM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - BSP',
    address: 'Address',
    clinicaddress: 'NO 60 GROUND FLOOR ,JALAN SPU 1,BANDAR SAUJANA PUTRA ,LEBUHRAYA ELITE',
    location: 'Location',
    cliniclocation: 'JENJAROM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI - KOTA DAMANSARA',
    subtitletext: 'KOTA DAMANSARA',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - KOTA DAMANSARA',
    address: 'Address',
    clinicaddress: 'NO 12 & 12 A GROUND FLOOR ,JALAN CAMAR 4/2 ,SEKSYEN 4',
    location: 'Location',
    cliniclocation: 'KOTA DAMANSARA',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI - SEMENYIH',
    subtitletext: 'SEMENYIH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - SEMENYIH',
    address: 'Address',
    clinicaddress: 'NO 23 GROUND FLOOR JALAN TPS 1/5 TAMAN PELANGI SEMENYIH',
    location: 'Location',
    cliniclocation: 'SEMENYIH',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
    Sesclist(
    titletext: 'KLINIK SITI - SHAH ALAM',
    subtitletext: 'SHAH ALAM',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - SHAH ALAM',
    address: 'Address',
    clinicaddress: 'B-7-G TINGKAT BAWAH, JALAN SERAI WANGI G 16/G SEKSYEN 16',
    location: 'Location',
    cliniclocation: 'SHAH ALAM',
    state: 'State',
    nameofstate: 'SELANGOR',
    ),
];