import 'package:flutter/material.dart';

class Wklsclist {
  final String clinic;
  final String clinicname;
  final String address;
  final String clinicaddress;
  final String location;
  final String cliniclocation;
  final String state;
  final String nameofstate;
  final String titletext;
  final String subtitletext;

  Wklsclist(
    {
    @required this.clinic,
    @required this.clinicname,
    @required this.address,
    @required this.clinicaddress,
    @required this.location,
    @required this.cliniclocation,
    @required this.state,
    @required this.nameofstate,
    @required this.titletext,
    @required this.subtitletext,
    }
  );
}
final WpKualaLumpurStateClinicList=[
  Wklsclist(
    titletext: 'KLINIK TAR',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK TAR',
    address: 'Address',
    clinicaddress: 'NO.329, JALAN TUANKU ABDUL RAHMAN',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDIVIRON PANDAN INDAH',
    subtitletext: 'PANDAN INDAH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIVIRON PANDAN INDAH',
    address: 'Address',
    clinicaddress: 'NO. 7A, JALAN PANDAN INDAH 4/8, PANDAN INDAH',
    location: 'Location',
    cliniclocation: 'PANDAN INDAH',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK INTER-MED',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK INTER-MED',
    address: 'Address',
    clinicaddress: '43, JALAN TUN TAN SIEW SIN',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK CITY',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CITY',
    address: 'Address',
    clinicaddress: 'NO.1, TAMAN CITY OFF JALAN KUCHING',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK AZHAR',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK AZHAR',
    address: 'Address',
    clinicaddress: '14-0-6 & 14-0-7 JALAN 5/112A ,TAMAN BUKIT ANGKASA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK TAN & LEE ( POLIKLINIK KUMPULAN CITY )',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK TAN & LEE ( POLIKLINIK KUMPULAN CITY )',
    address: 'Address',
    clinicaddress: 'NO 11-G JALAN 5/116 B ,KUCHAI ENTREPRENEURS PARK ,JALAN KUCHAI LAMA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'THE KL CLINIC',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'THE KL CLINIC',
    address: 'Address',
    clinicaddress: 'STESEN KERETAPI LAMA ,JALAN SULTAN HISHAMUDDIN',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'THE KL CLINIC - MENARA HAP SENG',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'THE KL CLINIC - MENARA HAP SENG',
    address: 'Address',
    clinicaddress: 'LOT NO.IM-02 LEVEL 1 ,MENARA HAP SENG 2 ,PLAZA HAP SENG ,NO 1 JALAN P.RAMLEE',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'THE KL CLINIC - EAST WING',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'THE KL CLINIC - EAST WING',
    address: 'Address',
    clinicaddress: 'MEZZANINE FLOOR ,EAST WING ,ROHAS PERKASA,NO 9 JALAN P.RAMLEE',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK CHOO',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CHOO',
    address: 'Address',
    clinicaddress: '14 BATU VILLAGE ,5TH MILES ,JALAN IPOH',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'DR.FATEH MOHAMED & RAKAN RAKAN SDN BHD',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'DR.FATEH MOHAMED & RAKAN RAKAN SDN BHD',
    address: 'Address',
    clinicaddress: 'SUITE 222 , TINGKAT 2 ,NO 86 JALAN MASJID INDIA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDILINK (MASJID INDIA) SDN BHD',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINK (MASJID INDIA) SDN BHD',
    address: 'Address',
    clinicaddress: '81-B-1, MEDAN BUNUS,JALAN MASJID INDIA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDILINK - WISMA MPL',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINK - WISMA MPL',
    address: 'Address',
    clinicaddress: 'LOT 1.33 TINGKAT 1 WISMA MPL ( HLA) ,JALAN RAJA CHULAN',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDILINK - WISMA MCA',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDILINK - WISMA MCA',
    address: 'Address',
    clinicaddress: 'SUITE 18.02 TINGKAT 18, WISMA MCA,163 JALAN AMPANG',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK DAMAI - JAKEL SQUARE',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DAMAI - JAKEL SQUARE',
    address: 'Address',
    clinicaddress: 'B-01(BASEMENT) JAKEL SQUARE,SIGNATURE B,JALAN MUNSHI ABDULLAH',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK ANTHONY',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK ANTHONY',
    address: 'Address',
    clinicaddress: '365-1 4 TH MILE , JALAN AMPANG',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK BAMZ HEALTHCARE',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BAMZ HEALTHCARE',
    address: 'Address',
    clinicaddress: 'NO.12 A GROUND FLOOR JALAN SRI JATI1, TAMAN SRI JATI OFF JALAN PUCHONG',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK HEALTHCARE',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK HEALTHCARE',
    address: 'Address',
    clinicaddress: 'N0.3 -G JALAN 2/137B, RESOURCE INDUSTRIAL CENTRE,5TH MILES OLD KLANG ROAD',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDICA',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDICA',
    address: 'Address',
    clinicaddress: 'NO.3, GROUND FLOOR, JALAN 6/55, BUKIT JALIL INTEGRATED BUSINESS PARK (BUKIT OUG)',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK PLAZA SPECIALIST SKIN CLINIC',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PLAZA SPECIALIST SKIN CLINIC',
    address: 'Address',
    clinicaddress: '56 B, 2ND FLOOR, JALAN BUKIT BINTANG',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK SRI PERMAI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SRI PERMAI',
    address: 'Address',
    clinicaddress: 'NO.5 JALAN 16 KAMPUNG CHERAS BARU.',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK KUCAI SDN.BHD',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KUCAI SDN.BHD',
    address: 'Address',
    clinicaddress: 'NO.43,JALAN KUCHAI MAJU 17 KUCHAI ENTREPRENEUR PARK',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'PUSAT PERUBATAN KOHILAL SDN.BHD',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'PUSAT PERUBATAN KOHILAL SDN.BHD',
    address: 'Address',
    clinicaddress: 'NO.225, JALAN NEGARA 2, TAMAN MELAWATI.',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK PERUBATAN SAMUEL',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PERUBATAN SAMUEL',
    address: 'Address',
    clinicaddress: '313,JALAN TUN RAZAK',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK MUC',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK MUC',
    address: 'Address',
    clinicaddress: 'NO.88A,JALAN ALOR',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MENARA TM',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MENARA TM',
    address: 'Address',
    clinicaddress: 'GROUND FLOOR,MENARA TM JALAN PANTAI BHARU',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK METRO (PERMAISURI)',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK METRO (PERMAISURI)',
    address: 'Address',
    clinicaddress: '23-G, JALAN SRI PERMAISURI 9, BANDAR SRI PERMAISURI',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK NEUMEDIK',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK NEUMEDIK',
    address: 'Address',
    clinicaddress: 'SUITE 1.01, 1 FLOOR WISMA MARAN NO.28 MEDAN PASAR',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'DR.LIM MEDICAL CLINIC',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'DR.LIM MEDICAL CLINIC',
    address: 'Address',
    clinicaddress: '17-2, THE BOULEVARD, MID VALLEY CITY LINGKARAN SYED PUTRA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK RAMABAI DAN SURGERI SDN BHD',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAMABAI DAN SURGERI SDN BHD',
    address: 'Address',
    clinicaddress: 'NO.14 JALAN BURUNG TIONG, TAMAN BUKIT MALURI, KEPONG',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK CENTRAL (WALTER GRENIER)',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK CENTRAL (WALTER GRENIER)',
    address: 'Address',
    clinicaddress: 'RETAIL 3,A-0-2(B) GROUND FLOOR BINTANG FAIR LANE RESIDENCE NO.23,JALAN PADANG WALTER GRENIER',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK SETAPAK DAN SURGERI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SETAPAK DAN SURGERI',
    address: 'Address',
    clinicaddress: 'NO.39, JALAN 1/27B, TAMAN DESA SETAPAK',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK CAHAYA',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK CAHAYA',
    address: 'Address',
    clinicaddress: 'NO.17, JALAN PANDAN PERDANA 4/5, PANDAN PERDANA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK DAN SURGERI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DAN SURGERI',
    address: 'Address',
    clinicaddress: 'NO.SSG -9, SRI SAUJANA APT, JALAN WANGSA PERMAI,',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK ANAND DAN SURGERI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK ANAND DAN SURGERI',
    address: 'Address',
    clinicaddress: 'NO.47 & 47A, JALAN PERDANA 6/4, PANDAN PERDANA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK SRI SENTOSA',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SRI SENTOSA',
    address: 'Address',
    clinicaddress: 'NO.9, JALAN 8A/133, TAMAN SRI SENTOSA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK MEDI-KULIT DAN SURGERI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK MEDI-KULIT DAN SURGERI',
    address: 'Address',
    clinicaddress: 'NO.89, JALAN METRO PERDANA BARAT 1, TAMAN USAHAWAN KEPONG UTARA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK SARAYA DAN SURGERI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SARAYA DAN SURGERI',
    address: 'Address',
    clinicaddress: 'NO.25 JALAN BUNGA TANJUNG 18 TAMAN SARAYA CHERAS',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK SENTRAL PERUBATAN & X-RAY',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SENTRAL PERUBATAN & X-RAY',
    address: 'Address',
    clinicaddress: 'UNIT 3, LEVEL 2, STESEN SENTRAL KUALA LUMPUR',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK CHIN CHEE YEONG',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CHIN CHEE YEONG',
    address: 'Address',
    clinicaddress: 'NO.34A, JALAN 6/18A, TAMAN MASTIARA, BATU 5 1/2, OFF JALAN IPOH',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK RAPHA GOODWILL',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAPHA GOODWILL',
    address: 'Address',
    clinicaddress: 'NO.147, JALAN SULTAN ABDUL SAMAD , BRICKFIELDS',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDIVIRON-CHERAS',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIVIRON-CHERAS',
    address: 'Address',
    clinicaddress: 'NO.30G, JALAN 2/10C, CHERAS BUSINESS CENTRE, BATU 5, JALAN CHERAS',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK HARTAMAS',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK HARTAMAS',
    address: 'Address',
    clinicaddress: 'NO.44, GROUND FLOOR, JALAN 27/70A, DESA SRI HARTAMAS',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK CHONG & SINGH',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CHONG & SINGH',
    address: 'Address',
    clinicaddress: '45 (GROUND FLOOR) JALAN 1/23F TAMAN TERATAI MEWAH, SETAPAK',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK SITI-WANGSA MELAWATI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI-WANGSA MELAWATI',
    address: 'Address',
    clinicaddress: 'NO.23 (GROUND FLOOR) JALAN WANGSA SETIA 1, WANGSA MELAWATI',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK KUCHAI AVENUE',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KUCHAI AVENUE',
    address: 'Address',
    clinicaddress: 'KA 2 1-2 KUCHAI AVENUE, NO.39, JALAN KUCHAI MAJU 13, KUCHAI ENT PARK',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK ZAZALI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK ZAZALI',
    address: 'Address',
    clinicaddress: 'NO 1, JALAN 6/2E TAMAN DANAU KOTA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MONT HOPE',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MONT HOPE',
    address: 'Address',
    clinicaddress: 'B2-03 PLAZA DAMAS 3, JALAN SRI HARTAMAS 1, SRI HARTAMAS',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK DAN PEMBEDAHAN BANDAR',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DAN PEMBEDAHAN BANDAR',
    address: 'Address',
    clinicaddress: 'G-16, RESIDENSI AWANI NO.27 JALAN SENTUL PERDANA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK MEDIPRIMA - KUALA LUMPUR',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK MEDIPRIMA - KUALA LUMPUR',
    address: 'Address',
    clinicaddress: '29, JALAN TUN MOHD FUAD 3 TAMAN TUN DR.ISMAIL',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK PERUBATAN MALAYA',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PERUBATAN MALAYA',
    address: 'Address',
    clinicaddress: 'NO.40, JALAN LEBOH AMPANG',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK MAHMOOD',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK MAHMOOD',
    address: 'Address',
    clinicaddress: '6-G, JALAN TASIK UTAMA 10, MEDAN NIAGA TASIK DAMAI, SUNGAI BESI',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK KELUARGA - WANGSA MAJU',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK KELUARGA - WANGSA MAJU',
    address: 'Address',
    clinicaddress: 'NO.28, JALAN 1A/27A, SECTION 1, WANGSA MAJU',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK INDAH',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK INDAH',
    address: 'Address',
    clinicaddress: 'NO.10, JALAN PANDAN INDAH 1/23D , PANDAN INDAH',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK SRI PRIMA - KL',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK SRI PRIMA - KL',
    address: 'Address',
    clinicaddress: 'NO.686, JALAN TUN PERAK',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK PUSRAWI MENARA FELDA',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PUSRAWI MENARA FELDA',
    address: 'Address',
    clinicaddress: 'LEVEL B1, MENARA FELDA, PLATINUM PARK NO.11, PERSIARAN KLCC, KUALA LUMPUR CITY SQUARE',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK PUSRAWI TAMAN PERMATA',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PUSRAWI TAMAN PERMATA',
    address: 'Address',
    clinicaddress: 'LOT2763A, JALAN CHANGKAT PERMATA, TAMAN PERMATA',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK PUSRAWI JALAN IPOH',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PUSRAWI JALAN IPOH',
    address: 'Address',
    clinicaddress: 'GF, NO.132 - 138, WISMA BAITULMAL, JALAN IPOH',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK SITI - TAMAN MELAWATI',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SITI - TAMAN MELAWATI',
    address: 'Address',
    clinicaddress: '9152 (GF), JALAN BANDAR 4, TAMAN MELAWATI',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'CITY HEALTH CARE SDN BHD',
    subtitletext: 'KUALA LUMPUR',
    clinic: 'Clinic Name',
    clinicname: 'CITY HEALTH CARE SDN BHD',
    address: 'Address',
    clinicaddress: 'LOT 202, LEVEL 2, MENARA HLA, NO.3, JALAN KIA PENG',
    location: 'Location',
    cliniclocation: 'KUALA LUMPUR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK LAI',
    subtitletext: 'BRICKFIELDS',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK LAI',
    address: 'Address',
    clinicaddress: 'NO. 8, JALAN THAMBIPILLAY, BRICKFIELDS, KUALA LUMPUR',
    location: 'Location',
    cliniclocation: 'BRICKFIELDS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK LAKSHMI',
    subtitletext: 'BRICKFIELDS',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK LAKSHMI',
    address: 'Address',
    clinicaddress: 'GROUND FLOOR, SCOTT SENTRAL SERVICE 4, LORONG PADANG BELIA, BRICKFIELDS, KUALA LUMPUR',
    location: 'Location',
    cliniclocation: 'BRICKFIELDS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDIK',
    subtitletext: 'TAMAN MELAWATI',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIK',
    address: 'Address',
    clinicaddress: 'NO. 9156, JALAN BANDAR 4 , TAMAN MELAWATI , KUALA LUMPUR',
    location: 'Location',
    cliniclocation: 'TAMAN MELAWATI',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK RAJ & RAKAN RAKAN',
    subtitletext: 'SENTUL',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK RAJ & RAKAN RAKAN',
    address: 'Address',
    clinicaddress: 'NO. 778, JALAN SENTUL',
    location: 'Location',
    cliniclocation: 'SENTUL',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK DRS ABRAHAM GEORGE & PARTNERS',
    subtitletext: 'DAMANSARA HEIGHTS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DRS ABRAHAM GEORGE & PARTNERS',
    address: 'Address',
    clinicaddress: 'LEVEL ONE MENARA MANULIFE RB, JALAN GELANGGANG , DAMANSARA HEIGHTS',
    location: 'Location',
    cliniclocation: 'DAMANSARA HEIGHTS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK DR ALYNA',
    subtitletext: 'WANGSA MAJU',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DR ALYNA',
    address: 'Address',
    clinicaddress: "NO. 6, JALAN WANGSA DELIMA 10, D' WANGSA, WANGSA MAJU, KUALA LUMPUR",
    location: 'Location',
    cliniclocation: 'WANGSA MAJU',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK HERO',
    subtitletext: 'DAMANSARA HEIGHTS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK HERO',
    address: 'Address',
    clinicaddress: "NO. 22-G, JALAN WANGSA DELIMA 11, D'WANGSA, WANGSA MAJU, KUALA LUMPUR",
    location: 'Location',
    cliniclocation: 'DAMANSARA HEIGHTS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK LEN SENG',
    subtitletext: 'CHERAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK LEN SENG',
    address: 'Address',
    clinicaddress: 'NO. 76-G, JALAN 1,TAMAN LEN SENG, CHERAS, KUALA LUMPUR',
    location: 'Location',
    cliniclocation: 'CHERAS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK METRO (FORMERLY KNOWN AS KLINIK HARMONI)',
    subtitletext: 'PANDAN INDAH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK METRO (FORMERLY KNOWN AS KLINIK HARMONI)',
    address: 'Address',
    clinicaddress: 'NO. 13B-G, JALAN PANDAN INDAH 3/3B, PANDAN INDAH',
    location: 'Location',
    cliniclocation: 'PANDAN INDAH',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK CAHAYA ( PANDAN ) SDN BHD',
    subtitletext: 'DESA PANDAN',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK CAHAYA ( PANDAN ) SDN BHD',
    address: 'Address',
    clinicaddress: 'NO 15, JALAN 2/76 C DESA PANDAN',
    location: 'Location',
    cliniclocation: 'DESA PANDAN',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK NATHAN DAN RAKAN RAKAN',
    subtitletext: 'BANGSAR',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK NATHAN DAN RAKAN RAKAN',
    address: 'Address',
    clinicaddress: 'NO.8 JALAN BANGSAR',
    location: 'Location',
    cliniclocation: 'BANGSAR',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK SRI MANJA - TUN SAMBANTHAN',
    subtitletext: 'BRICKFIELDS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK SRI MANJA - TUN SAMBANTHAN',
    address: 'Address',
    clinicaddress: '178 JALAN TUN SAMBANTHAN',
    location: 'Location',
    cliniclocation: 'BRICKFIELDS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDIVIRON',
    subtitletext: 'PANDAN INDAH',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIVIRON',
    address: 'Address',
    clinicaddress: '7G,JALAN PANDAN INDAH 4/8 ,PANDAN INDAH',
    location: 'Location',
    cliniclocation: 'PANDAN INDAH',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK DADDY',
    subtitletext: 'SETAPAK',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DADDY',
    address: 'Address',
    clinicaddress: 'NO.21G JALAN MELATI UTAMA 4, MELATI UTAMA',
    location: 'Location',
    cliniclocation: 'SETAPAK',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK AZZAM',
    subtitletext: 'SETAPAK',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK AZZAM',
    address: 'Address',
    clinicaddress: 'D-70 USAHAWAN GENTING KLANG,PLAZA CRYSTAL VILLE ,JALAN DANGAU NIAGA 1,TAMAN DANAU KOTA',
    location: 'Location',
    cliniclocation: 'SETAPAK',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'MEDIC CLINIC',
    subtitletext: 'KEPONG',
    clinic: 'Clinic Name',
    clinicname: 'MEDIC CLINIC',
    address: 'Address',
    clinicaddress: 'UNIT NO.1-8 LEVEL 1, PLAZA MENJALARA IDAMAN ,NO.1 JALAN MENJALARA IDAMAN, BANDAR MENJALARA',
    location: 'Location',
    cliniclocation: 'KEPONG',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'UNITED HEALTH CLINIC',
    subtitletext: 'KEPONG',
    clinic: 'Clinic Name',
    clinicname: 'UNITED HEALTH CLINIC',
    address: 'Address',
    clinicaddress: 'G-02 RESIDENSI HENGE,JALAN METRO PERDANA BARAT,TAMAN METROPOLITAN',
    location: 'Location',
    cliniclocation: 'KEPONG',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MAHA & RAO',
    subtitletext: 'CHERAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MAHA & RAO',
    address: 'Address',
    clinicaddress: '19 JALAN DAMAI PERDANA 1/9C ,BANDAR DAMAI PERDANA',
    location: 'Location',
    cliniclocation: 'CHERAS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK CHERAS BARU',
    subtitletext: 'CHERAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK CHERAS BARU',
    address: 'Address',
    clinicaddress: 'NO.19 JALAN BUNGA TANJUNG 7,TAMAN MUDA',
    location: 'Location',
    cliniclocation: 'CHERAS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK METRO (TAMAN IKAN EMAS)',
    subtitletext: 'CHERAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK METRO (TAMAN IKAN EMAS)',
    address: 'Address',
    clinicaddress: 'NO.92-G, AMBER BUSINESS PLAZA 2, JALAN JELAWAT 1,',
    location: 'Location',
    cliniclocation: 'CHERAS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK TRUCARE',
    subtitletext: 'SENTUL',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK TRUCARE',
    address: 'Address',
    clinicaddress: 'G-67 MAXIM CITYLIGHTS, JALAN SENTUL PASAR',
    location: 'Location',
    cliniclocation: 'SENTUL',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK BABA SDN.BHD',
    subtitletext: 'PUCHONG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK BABA SDN.BHD',
    address: 'Address',
    clinicaddress: 'NO.12, JALAN KINRARA, TAMAN KINRARA BATU7,JALAN PUCHONG',
    location: 'Location',
    cliniclocation: 'PUCHONG',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK DAMAI PERDANA',
    subtitletext: 'CHERAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK DAMAI PERDANA',
    address: 'Address',
    clinicaddress: 'NO.8 JALAN DAMAI PERDANA 1/9A BANDAR DAMAI PERDANA',
    location: 'Location',
    cliniclocation: 'CHERAS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK DHALIWAL',
    subtitletext: 'CHERAS',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK DHALIWAL',
    address: 'Address',
    clinicaddress: 'NO.35, JALAN SELIMANG, TAMAN TENAGA',
    location: 'Location',
    cliniclocation: 'CHERAS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'POLIKLINIK MEDAN PUTRA',
    subtitletext: 'KEPONG',
    clinic: 'Clinic Name',
    clinicname: 'POLIKLINIK MEDAN PUTRA',
    address: 'Address',
    clinicaddress: '51G, JALAN MEDAN PUTRA 1, MEDAN PUTRA BUSINESS CENTRE, BANDAR MANJALARA',
    location: 'Location',
    cliniclocation: 'KEPONG',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK NADIA',
    subtitletext: 'BRICKFIELDS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK NADIA',
    address: 'Address',
    clinicaddress: 'NO.5A, GROUND FLOOR, WISMA LEOPAD, JALAN TUN SAMBANTHAN',
    location: 'Location',
    cliniclocation: 'BRICKFIELDS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK PERKASA',
    subtitletext: 'CHERAS',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK PERKASA',
    address: 'Address',
    clinicaddress: 'NO.94, JALAN 4/91, TAMAN SHAMELIN PERKASA',
    location: 'Location',
    cliniclocation: 'CHERAS',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
    Wklsclist(
    titletext: 'KLINIK MEDIVIRON-AMPANG WATERFRONT',
    subtitletext: 'AMPANG',
    clinic: 'Clinic Name',
    clinicname: 'KLINIK MEDIVIRON-AMPANG WATERFRONT',
    address: 'Address',
    clinicaddress: 'NO. 13, AWF2 AMPANG WATERFRONT',
    location: 'Location',
    cliniclocation: 'AMPANG',
    state: 'State',
    nameofstate: 'WP KUALA LUMPUR',
    ),
];